import type { CredentialListItem } from '@cairn/shared'

export function credentialFixture(index = 1): CredentialListItem {
  const id = `11111111-1111-4111-8111-${String(index).padStart(12, '0')}`
  return {
    id,
    type: 'target_password',
    source: 'target_account',
    name: `账号 ${index}`,
    safeIdentifier: `00${index}`,
    subjectLabel: '业务系统',
    targetId: '22222222-2222-4222-8222-222222222222',
    targetAccountId: id,
    target: {
      id: '22222222-2222-4222-8222-222222222222',
      code: 'CRM',
      name: '业务系统',
      accountId: id,
      accountName: `账号 ${index}`,
      username: `00${index}`,
    },
    hasPassword: true,
    revision: 1,
    managementStatus: 'active',
    maintenanceStatus: 'permanent',
    maintenanceDueAt: null,
    validityStartedAt: '2026-01-01T00:00:00.000Z',
    validityPolicy: { mode: 'permanent', amount: null, timeZone: null },
    issuerExpiresAt: null,
    issuerExpirySource: 'unknown',
    verificationStatus: 'pending',
    identityBindingStatus: 'confirmed',
    ownerConsoleAccountId: null,
    ownerDisplayName: null,
    ownerStatus: 'unclaimed',
    session: {
      browser: 'unprepared',
      auth: 'unknown',
      identityState: 'UNVERIFIED',
      occupancy: 'idle',
      sessionId: null,
      generation: null,
      observedAt: null,
      lastAuthCheckedAt: null,
      lastAuthSuccessAt: null,
      occupyingLabel: null,
    },
    capabilities: {
      canReplace: true,
      canSetMaintenance: true,
      canVerify: false,
      canDisable: true,
      externallyRenewed: false,
      canDelete: true,
      canEditAccount: true,
      canImport: true,
    },
    currentVersionId: '33333333-3333-4333-8333-333333333333',
    updatedAt: '2026-01-01T00:00:00.000Z',
    createdAt: '2026-01-01T00:00:00.000Z',
  }
}
