-- Native baseline at logical schema 0015. IDs are generated by the application.

CREATE TABLE "attempts" (
  "id" TEXT NOT NULL,
  "step_run_id" TEXT NOT NULL,
  "attempt_no" INTEGER NOT NULL CHECK ("attempt_no" IS NULL OR (typeof("attempt_no") = 'integer' AND "attempt_no" BETWEEN -2147483648 AND 2147483647)),
  "status" TEXT NOT NULL,
  "started_at" TEXT NOT NULL,
  "finished_at" TEXT,
  "output" TEXT CHECK ("output" IS NULL OR json_valid("output")),
  "error" TEXT CHECK ("error" IS NULL OR json_valid("error")),
  CONSTRAINT "attempts_no_check" CHECK ((attempt_no >= 1)),
  CONSTRAINT "attempts_pkey" PRIMARY KEY (id),
  CONSTRAINT "attempts_status_check" CHECK ((status IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED'))),
  CONSTRAINT "attempts_step_run_id_fkey" FOREIGN KEY (step_run_id) REFERENCES step_runs(id) ON DELETE RESTRICT
);

CREATE TABLE "browser_sessions" (
  "id" TEXT NOT NULL,
  "target_id" TEXT NOT NULL,
  "target_account_id" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "health" TEXT NOT NULL DEFAULT 'UNKNOWN',
  "auth_state" TEXT NOT NULL DEFAULT 'UNKNOWN',
  "owner_worker_id" TEXT NOT NULL,
  "generation" INTEGER NOT NULL CHECK ("generation" IS NULL OR (typeof("generation") = 'integer' AND "generation" BETWEEN -2147483648 AND 2147483647)),
  "fencing_token" INTEGER NOT NULL DEFAULT 0 CHECK ("fencing_token" IS NULL OR (typeof("fencing_token") = 'integer' AND "fencing_token" BETWEEN -2147483648 AND 2147483647)),
  "version" INTEGER NOT NULL DEFAULT 0 CHECK ("version" IS NULL OR (typeof("version") = 'integer' AND "version" BETWEEN -2147483648 AND 2147483647)),
  "profile_key" TEXT NOT NULL,
  "reuse_policy" TEXT NOT NULL,
  "idle_ttl_seconds" INTEGER NOT NULL CHECK ("idle_ttl_seconds" IS NULL OR (typeof("idle_ttl_seconds") = 'integer' AND "idle_ttl_seconds" BETWEEN -2147483648 AND 2147483647)),
  "max_lifetime_seconds" INTEGER NOT NULL CHECK ("max_lifetime_seconds" IS NULL OR (typeof("max_lifetime_seconds") = 'integer' AND "max_lifetime_seconds" BETWEEN -2147483648 AND 2147483647)),
  "expires_at" TEXT NOT NULL,
  "last_used_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "auth_hold_worker_id" TEXT,
  "auth_hold_expires_at" TEXT,
  "close_reason" TEXT,
  "closed_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CONSTRAINT "browser_sessions_auth_hold_check" CHECK (((auth_hold_worker_id IS NULL) = (auth_hold_expires_at IS NULL))),
  CONSTRAINT "browser_sessions_auth_state_check" CHECK ((auth_state IN ('UNKNOWN', 'AUTHENTICATED', 'EXPIRED'))),
  CONSTRAINT "browser_sessions_closed_check" CHECK (((status <> 'CLOSED') OR ((closed_at IS NOT NULL) AND (close_reason IS NOT NULL)))),
  CONSTRAINT "browser_sessions_generation_check" CHECK (((generation >= 1) AND (fencing_token >= 0) AND (version >= 0))),
  CONSTRAINT "browser_sessions_health_check" CHECK ((health IN ('UNKNOWN', 'HEALTHY', 'UNHEALTHY'))),
  CONSTRAINT "browser_sessions_pkey" PRIMARY KEY (id),
  CONSTRAINT "browser_sessions_reuse_policy_check" CHECK ((reuse_policy IN ('REUSE_PAGE', 'NEW_PAGE', 'RECREATE_SESSION'))),
  CONSTRAINT "browser_sessions_status_check" CHECK ((status IN ('CREATING', 'OPEN', 'CLOSING', 'CLOSED', 'LOST'))),
  CONSTRAINT "browser_sessions_target_account_fkey" FOREIGN KEY (target_account_id, target_id) REFERENCES target_accounts(id, target_id) ON DELETE RESTRICT,
  CONSTRAINT "browser_sessions_ttl_check" CHECK (((idle_ttl_seconds > 0) AND (max_lifetime_seconds > idle_ttl_seconds)))
);

CREATE TABLE "console_account_roles" (
  "console_account_id" TEXT NOT NULL,
  "console_role_id" TEXT NOT NULL,
  "assigned_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "assigned_by_console_account_id" TEXT,
  CONSTRAINT "console_account_roles_assigned_by_console_account_id_fkey" FOREIGN KEY (assigned_by_console_account_id) REFERENCES console_accounts(id) ON DELETE SET NULL,
  CONSTRAINT "console_account_roles_console_account_id_fkey" FOREIGN KEY (console_account_id) REFERENCES console_accounts(id) ON DELETE CASCADE,
  CONSTRAINT "console_account_roles_console_role_id_fkey" FOREIGN KEY (console_role_id) REFERENCES console_roles(id) ON DELETE RESTRICT,
  CONSTRAINT "console_account_roles_pkey" PRIMARY KEY (console_account_id, console_role_id)
);

CREATE TABLE "console_accounts" (
  "id" TEXT NOT NULL,
  "display_name" TEXT NOT NULL,
  "email" TEXT,
  "status" TEXT NOT NULL DEFAULT 'active',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CONSTRAINT "console_accounts_pkey" PRIMARY KEY (id),
  CONSTRAINT "console_accounts_status_check" CHECK ((status IN ('active', 'disabled')))
);

CREATE TABLE "console_audit_events" (
  "id" TEXT NOT NULL,
  "actor_console_account_id" TEXT,
  "action" TEXT NOT NULL,
  "resource" TEXT NOT NULL,
  "resource_id" TEXT,
  "summary" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CONSTRAINT "console_audit_events_actor_console_account_id_fkey" FOREIGN KEY (actor_console_account_id) REFERENCES console_accounts(id) ON DELETE SET NULL,
  CONSTRAINT "console_audit_events_pkey" PRIMARY KEY (id)
);

CREATE TABLE "console_identities" (
  "id" TEXT NOT NULL,
  "console_account_id" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "secret" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "last_used_at" TEXT,
  CONSTRAINT "console_identities_console_account_id_fkey" FOREIGN KEY (console_account_id) REFERENCES console_accounts(id) ON DELETE CASCADE,
  CONSTRAINT "console_identities_pkey" PRIMARY KEY (id),
  CONSTRAINT "console_identities_secret_check" CHECK ((((provider = 'local') AND (secret IS NOT NULL)) OR ((provider <> 'local') AND (secret IS NULL))))
);

CREATE TABLE "console_role_permissions" (
  "console_role_id" TEXT NOT NULL,
  "permission" TEXT NOT NULL,
  CONSTRAINT "console_role_permissions_console_role_id_fkey" FOREIGN KEY (console_role_id) REFERENCES console_roles(id) ON DELETE CASCADE,
  CONSTRAINT "console_role_permissions_pkey" PRIMARY KEY (console_role_id, permission)
);

CREATE TABLE "console_roles" (
  "id" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "kind" TEXT NOT NULL DEFAULT 'custom',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CONSTRAINT "console_roles_kind_check" CHECK ((kind IN ('system', 'custom'))),
  CONSTRAINT "console_roles_pkey" PRIMARY KEY (id)
);

CREATE TABLE "evidences" (
  "id" TEXT NOT NULL,
  "run_id" TEXT NOT NULL,
  "step_run_id" TEXT,
  "attempt_id" TEXT,
  "type" TEXT NOT NULL,
  "schema_version" INTEGER NOT NULL DEFAULT 1 CHECK ("schema_version" IS NULL OR (typeof("schema_version") = 'integer' AND "schema_version" BETWEEN -2147483648 AND 2147483647)),
  "payload" TEXT CHECK ("payload" IS NULL OR json_valid("payload")),
  "object_key" TEXT,
  "content_type" TEXT,
  "byte_size" INTEGER CHECK ("byte_size" IS NULL OR (typeof("byte_size") = 'integer' AND "byte_size" BETWEEN -2147483648 AND 2147483647)),
  "digest" TEXT,
  "missing_reason" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "status" TEXT NOT NULL DEFAULT 'available',
  "object_id" TEXT,
  "upload_attempts" INTEGER NOT NULL DEFAULT 0 CHECK ("upload_attempts" IS NULL OR (typeof("upload_attempts") = 'integer' AND "upload_attempts" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "evidences_attempt_id_fkey" FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE RESTRICT,
  CONSTRAINT "evidences_object_id_stored_objects_fkey" FOREIGN KEY (object_id) REFERENCES stored_objects(id) ON DELETE RESTRICT,
  CONSTRAINT "evidences_object_key_stored_objects_fkey" FOREIGN KEY (object_key) REFERENCES stored_objects(object_key) ON DELETE RESTRICT,
  CONSTRAINT "evidences_pkey" PRIMARY KEY (id),
  CONSTRAINT "evidences_run_id_fkey" FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE RESTRICT,
  CONSTRAINT "evidences_status_check" CHECK ((status IN ('pending', 'available', 'missing'))),
  CONSTRAINT "evidences_status_missing_reason_check" CHECK ((((status = 'missing') AND (missing_reason IS NOT NULL)) OR ((status <> 'missing') AND (missing_reason IS NULL)))),
  CONSTRAINT "evidences_step_run_id_fkey" FOREIGN KEY (step_run_id) REFERENCES step_runs(id) ON DELETE RESTRICT,
  CONSTRAINT "evidences_type_check" CHECK ((type IN ('input', 'output', 'error', 'screenshot', 'log', 'trace'))),
  CONSTRAINT "evidences_upload_attempts_check" CHECK ((upload_attempts >= 0))
);

CREATE TABLE "recording_drafts" (
  "id" TEXT NOT NULL,
  "target_id" TEXT NOT NULL,
  "created_by_console_account_id" TEXT NOT NULL,
  "recording_id" TEXT NOT NULL,
  "source_version" TEXT NOT NULL,
  "idempotency_key" TEXT NOT NULL,
  "payload_digest" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "event_count" INTEGER NOT NULL CHECK ("event_count" IS NULL OR (typeof("event_count") = 'integer' AND "event_count" BETWEEN -2147483648 AND 2147483647)),
  "item_count" INTEGER NOT NULL CHECK ("item_count" IS NULL OR (typeof("item_count") = 'integer' AND "item_count" BETWEEN -2147483648 AND 2147483647)),
  "unresolved_count" INTEGER NOT NULL CHECK ("unresolved_count" IS NULL OR (typeof("unresolved_count") = 'integer' AND "unresolved_count" BETWEEN -2147483648 AND 2147483647)),
  "events" TEXT NOT NULL CHECK ("events" IS NULL OR json_valid("events")),
  "items" TEXT NOT NULL CHECK ("items" IS NULL OR json_valid("items")),
  "diagnostics" TEXT NOT NULL CHECK ("diagnostics" IS NULL OR json_valid("diagnostics")),
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CONSTRAINT "recording_drafts_created_by_console_account_id_fkey" FOREIGN KEY (created_by_console_account_id) REFERENCES console_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT "recording_drafts_diagnostics_array" CHECK ((json_type("diagnostics") = 'array')),
  CONSTRAINT "recording_drafts_events_array" CHECK ((json_type("events") = 'array')),
  CONSTRAINT "recording_drafts_items_array" CHECK ((json_type("items") = 'array')),
  CONSTRAINT "recording_drafts_pkey" PRIMARY KEY (id),
  CONSTRAINT "recording_drafts_target_id_fkey" FOREIGN KEY (target_id) REFERENCES targets(id) ON DELETE RESTRICT
);

CREATE TABLE "run_leases" (
  "id" TEXT NOT NULL,
  "run_id" TEXT NOT NULL,
  "fencing_token" INTEGER NOT NULL CHECK ("fencing_token" IS NULL OR (typeof("fencing_token") = 'integer' AND "fencing_token" BETWEEN -2147483648 AND 2147483647)),
  "holder_worker_id" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "acquired_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "heartbeat_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "expires_at" TEXT NOT NULL,
  "released_at" TEXT,
  "release_reason" TEXT,
  CONSTRAINT "run_leases_pkey" PRIMARY KEY (id),
  CONSTRAINT "run_leases_released_check" CHECK (((status = 'ACTIVE') = (released_at IS NULL))),
  CONSTRAINT "run_leases_run_id_fkey" FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE RESTRICT,
  CONSTRAINT "run_leases_status_check" CHECK ((status IN ('ACTIVE', 'RELEASED', 'EXPIRED', 'REVOKED'))),
  CONSTRAINT "run_leases_token_check" CHECK ((fencing_token >= 1))
);

CREATE TABLE "runs" (
  "id" TEXT NOT NULL,
  "target_id" TEXT NOT NULL,
  "scenario_id" TEXT NOT NULL,
  "scenario_version_id" TEXT NOT NULL,
  "target_account_id" TEXT,
  "created_by_console_account_id" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "cancel_requested_at" TEXT,
  "started_at" TEXT,
  "finished_at" TEXT,
  "snapshot" TEXT NOT NULL CHECK ("snapshot" IS NULL OR json_valid("snapshot")),
  "snapshot_digest" TEXT NOT NULL,
  "context" TEXT NOT NULL CHECK ("context" IS NULL OR json_valid("context")),
  "idempotency_key" TEXT,
  "idempotency_digest" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "evidence_status" TEXT NOT NULL DEFAULT 'PENDING',
  CONSTRAINT "runs_created_by_console_account_id_fkey" FOREIGN KEY (created_by_console_account_id) REFERENCES console_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT "runs_evidence_status_check" CHECK ((evidence_status IN ('PENDING', 'COMPLETE', 'INCOMPLETE'))),
  CONSTRAINT "runs_idempotency_pair" CHECK (((idempotency_key IS NULL) = (idempotency_digest IS NULL))),
  CONSTRAINT "runs_pkey" PRIMARY KEY (id),
  CONSTRAINT "runs_scenario_id_fkey" FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE RESTRICT,
  CONSTRAINT "runs_scenario_version_id_fkey" FOREIGN KEY (scenario_version_id) REFERENCES scenario_versions(id) ON DELETE RESTRICT,
  CONSTRAINT "runs_status_check" CHECK ((status IN ('QUEUED', 'RUNNING', 'RECOVERING', 'WAITING_FOR_AUTH', 'NEEDS_REVIEW', 'SUCCEEDED', 'FAILED', 'CANCELLED'))),
  CONSTRAINT "runs_target_account_id_fkey" FOREIGN KEY (target_account_id) REFERENCES target_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT "runs_target_id_fkey" FOREIGN KEY (target_id) REFERENCES targets(id) ON DELETE RESTRICT
);

CREATE TABLE "scenario_drafts" (
  "scenario_id" TEXT NOT NULL,
  "revision" INTEGER NOT NULL CHECK ("revision" IS NULL OR (typeof("revision") = 'integer' AND "revision" BETWEEN -2147483648 AND 2147483647)),
  "document" TEXT NOT NULL CHECK ("document" IS NULL OR json_valid("document")),
  "updated_by_console_account_id" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CONSTRAINT "scenario_drafts_document_object" CHECK ((json_type("document") = 'object')),
  CONSTRAINT "scenario_drafts_pkey" PRIMARY KEY (scenario_id),
  CONSTRAINT "scenario_drafts_revision_check" CHECK ((revision >= 1)),
  CONSTRAINT "scenario_drafts_scenario_id_fkey" FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE RESTRICT,
  CONSTRAINT "scenario_drafts_updated_by_console_account_id_fkey" FOREIGN KEY (updated_by_console_account_id) REFERENCES console_accounts(id) ON DELETE RESTRICT
);

CREATE TABLE "scenario_versions" (
  "id" TEXT NOT NULL,
  "scenario_id" TEXT NOT NULL,
  "version_no" INTEGER CHECK ("version_no" IS NULL OR (typeof("version_no") = 'integer' AND "version_no" BETWEEN -2147483648 AND 2147483647)),
  "definition" TEXT NOT NULL CHECK ("definition" IS NULL OR json_valid("definition")),
  "created_by_console_account_id" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "kind" TEXT NOT NULL DEFAULT 'published',
  "compiler_version" INTEGER NOT NULL DEFAULT 1 CHECK ("compiler_version" IS NULL OR (typeof("compiler_version") = 'integer' AND "compiler_version" BETWEEN -2147483648 AND 2147483647)),
  "source_digest" TEXT NOT NULL,
  CONSTRAINT "scenario_versions_created_by_console_account_id_fkey" FOREIGN KEY (created_by_console_account_id) REFERENCES console_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT "scenario_versions_definition_object" CHECK ((json_type("definition") = 'object')),
  CONSTRAINT "scenario_versions_kind_check" CHECK ((kind IN ('published', 'trial'))),
  CONSTRAINT "scenario_versions_no_check" CHECK ((version_no >= 1)),
  CONSTRAINT "scenario_versions_pkey" PRIMARY KEY (id),
  CONSTRAINT "scenario_versions_published_no_check" CHECK ((((kind = 'published') AND (version_no IS NOT NULL)) OR ((kind = 'trial') AND (version_no IS NULL)))),
  CONSTRAINT "scenario_versions_scenario_id_fkey" FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE RESTRICT
);

CREATE TABLE "scenarios" (
  "id" TEXT NOT NULL,
  "target_id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'active',
  "created_by_console_account_id" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CONSTRAINT "scenarios_created_by_console_account_id_fkey" FOREIGN KEY (created_by_console_account_id) REFERENCES console_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT "scenarios_pkey" PRIMARY KEY (id),
  CONSTRAINT "scenarios_status_check" CHECK ((status IN ('active', 'disabled'))),
  CONSTRAINT "scenarios_target_id_fkey" FOREIGN KEY (target_id) REFERENCES targets(id) ON DELETE RESTRICT
);

CREATE TABLE "secrets" (
  "id" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "ciphertext" BLOB NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CONSTRAINT "secrets_pkey" PRIMARY KEY (id)
);

CREATE TABLE "session_leases" (
  "id" TEXT NOT NULL,
  "session_id" TEXT NOT NULL,
  "session_generation" INTEGER NOT NULL CHECK ("session_generation" IS NULL OR (typeof("session_generation") = 'integer' AND "session_generation" BETWEEN -2147483648 AND 2147483647)),
  "session_fencing_token" INTEGER NOT NULL CHECK ("session_fencing_token" IS NULL OR (typeof("session_fencing_token") = 'integer' AND "session_fencing_token" BETWEEN -2147483648 AND 2147483647)),
  "run_id" TEXT NOT NULL,
  "run_fencing_token" INTEGER CHECK ("run_fencing_token" IS NULL OR (typeof("run_fencing_token") = 'integer' AND "run_fencing_token" BETWEEN -2147483648 AND 2147483647)),
  "holder_worker_id" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "acquired_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "heartbeat_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "expires_at" TEXT NOT NULL,
  "released_at" TEXT,
  "release_reason" TEXT,
  CONSTRAINT "session_leases_fencing_check" CHECK (((session_generation >= 1) AND (session_fencing_token >= 1) AND ((run_fencing_token IS NULL) OR (run_fencing_token >= 1)))),
  CONSTRAINT "session_leases_pkey" PRIMARY KEY (id),
  CONSTRAINT "session_leases_released_check" CHECK (((status = 'ACTIVE') = (released_at IS NULL))),
  CONSTRAINT "session_leases_run_fencing_active_check" CHECK (((status <> 'ACTIVE') OR (run_fencing_token IS NOT NULL))),
  CONSTRAINT "session_leases_run_id_fkey" FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE RESTRICT,
  CONSTRAINT "session_leases_session_id_fkey" FOREIGN KEY (session_id) REFERENCES browser_sessions(id) ON DELETE RESTRICT,
  CONSTRAINT "session_leases_status_check" CHECK ((status IN ('ACTIVE', 'RELEASED', 'EXPIRED', 'REVOKED')))
);

CREATE TABLE "step_runs" (
  "id" TEXT NOT NULL,
  "run_id" TEXT NOT NULL,
  "step_id" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL CHECK ("ordinal" IS NULL OR (typeof("ordinal") = 'integer' AND "ordinal" BETWEEN -2147483648 AND 2147483647)),
  "status" TEXT NOT NULL,
  "started_at" TEXT,
  "finished_at" TEXT,
  CONSTRAINT "step_runs_ordinal_check" CHECK ((ordinal >= 0)),
  CONSTRAINT "step_runs_pkey" PRIMARY KEY (id),
  CONSTRAINT "step_runs_run_id_fkey" FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE RESTRICT,
  CONSTRAINT "step_runs_status_check" CHECK ((status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', 'CANCELLED')))
);

CREATE TABLE "stored_objects" (
  "id" TEXT NOT NULL,
  "object_key" TEXT NOT NULL,
  "run_id" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "content_type" TEXT,
  "byte_size" INTEGER CHECK ("byte_size" IS NULL OR (typeof("byte_size") = 'integer' AND "byte_size" BETWEEN -2147483648 AND 2147483647)),
  "digest" TEXT,
  "retain_until" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "available_at" TEXT,
  "purged_at" TEXT,
  "purge_reason" TEXT,
  "purge_attempts" INTEGER NOT NULL DEFAULT 0 CHECK ("purge_attempts" IS NULL OR (typeof("purge_attempts") = 'integer' AND "purge_attempts" BETWEEN -2147483648 AND 2147483647)),
  "last_purge_error_at" TEXT,
  CONSTRAINT "stored_objects_byte_size_check" CHECK (((byte_size IS NULL) OR (byte_size >= 0))),
  CONSTRAINT "stored_objects_pkey" PRIMARY KEY (id),
  CONSTRAINT "stored_objects_purge_reason_check" CHECK (((purge_reason IS NULL) OR (purge_reason IN ('expired', 'upload_incomplete')))),
  CONSTRAINT "stored_objects_run_id_fkey" FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE RESTRICT,
  CONSTRAINT "stored_objects_status_check" CHECK ((status IN ('pending', 'available', 'purged')))
);

CREATE TABLE "target_accounts" (
  "id" TEXT NOT NULL,
  "target_id" TEXT NOT NULL,
  "display_name" TEXT NOT NULL,
  "username" TEXT NOT NULL,
  "secret_provider" TEXT,
  "secret_id" TEXT,
  "status" TEXT NOT NULL DEFAULT 'active',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CONSTRAINT "target_accounts_pkey" PRIMARY KEY (id),
  CONSTRAINT "target_accounts_secret_id_fkey" FOREIGN KEY (secret_id) REFERENCES secrets(id) ON DELETE RESTRICT,
  CONSTRAINT "target_accounts_secret_ref_pair" CHECK ((((secret_id IS NULL) AND (secret_provider IS NULL)) OR ((secret_id IS NOT NULL) AND (secret_provider IS NOT NULL)))),
  CONSTRAINT "target_accounts_status_check" CHECK ((status IN ('active', 'disabled'))),
  CONSTRAINT "target_accounts_target_id_fkey" FOREIGN KEY (target_id) REFERENCES targets(id) ON DELETE RESTRICT
);

CREATE TABLE "targets" (
  "id" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "entry_url" TEXT NOT NULL,
  "login_url" TEXT,
  "auth_method" TEXT NOT NULL DEFAULT 'password',
  "captcha_mode" TEXT NOT NULL DEFAULT 'none',
  "status" TEXT NOT NULL DEFAULT 'active',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "login_fields" TEXT CHECK ("login_fields" IS NULL OR json_valid("login_fields")),
  CONSTRAINT "targets_auth_method_check" CHECK ((auth_method IN ('password', 'manual'))),
  CONSTRAINT "targets_captcha_mode_check" CHECK ((captcha_mode IN ('none', 'image', 'slider', 'sms', 'other'))),
  CONSTRAINT "targets_login_fields_object" CHECK (((login_fields IS NULL) OR (json_type("login_fields") = 'object'))),
  CONSTRAINT "targets_pkey" PRIMARY KEY (id),
  CONSTRAINT "targets_status_check" CHECK ((status IN ('active', 'disabled')))
);

CREATE TABLE "workers" (
  "id" TEXT NOT NULL,
  "instance_id" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "capacity" INTEGER NOT NULL CHECK ("capacity" IS NULL OR (typeof("capacity") = 'integer' AND "capacity" BETWEEN -2147483648 AND 2147483647)),
  "heartbeat_at" TEXT NOT NULL,
  "started_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "stopped_at" TEXT,
  "max_sessions" INTEGER NOT NULL DEFAULT 2 CHECK ("max_sessions" IS NULL OR (typeof("max_sessions") = 'integer' AND "max_sessions" BETWEEN -2147483648 AND 2147483647)),
  CONSTRAINT "workers_capacity_check" CHECK ((capacity >= 1)),
  CONSTRAINT "workers_max_sessions_check" CHECK ((max_sessions >= 1)),
  CONSTRAINT "workers_pkey" PRIMARY KEY (id),
  CONSTRAINT "workers_status_check" CHECK ((status IN ('READY', 'DRAINING', 'STOPPED', 'LOST')))
);

CREATE UNIQUE INDEX attempts_step_no_idx ON attempts (step_run_id, attempt_no);

CREATE UNIQUE INDEX browser_sessions_key_live_idx ON browser_sessions (target_id, target_account_id) WHERE (status IN ('CREATING', 'OPEN', 'CLOSING', 'LOST'));

CREATE INDEX browser_sessions_owner_idx ON browser_sessions (owner_worker_id, status);

CREATE INDEX browser_sessions_reap_idx ON browser_sessions (status, last_used_at) WHERE (status = 'OPEN');

CREATE INDEX console_account_roles_role_idx ON console_account_roles (console_role_id);

CREATE UNIQUE INDEX console_accounts_email_idx ON console_accounts (lower(email)) WHERE (email IS NOT NULL);

CREATE INDEX console_audit_events_actor_idx ON console_audit_events (actor_console_account_id);

CREATE INDEX console_audit_events_created_idx ON console_audit_events (created_at DESC);

CREATE INDEX console_identities_account_idx ON console_identities (console_account_id);

CREATE UNIQUE INDEX console_identities_provider_subject_idx ON console_identities (provider, subject);

CREATE INDEX console_role_permissions_perm_idx ON console_role_permissions (permission);

CREATE UNIQUE INDEX console_roles_key_idx ON console_roles ("key");

CREATE INDEX evidences_attempt_id_idx ON evidences (attempt_id);

CREATE INDEX evidences_run_created_idx ON evidences (run_id, created_at);

CREATE UNIQUE INDEX evidences_run_incomplete_idx ON evidences (run_id) WHERE ((type = 'error') AND (json_extract(payload, '$.code') = 'EVIDENCE_INCOMPLETE'));

CREATE INDEX evidences_status_idx ON evidences (status, created_at);

CREATE UNIQUE INDEX recording_drafts_actor_idempotency_idx ON recording_drafts (created_by_console_account_id, idempotency_key);

CREATE INDEX recording_drafts_created_at_idx ON recording_drafts (created_at);

CREATE INDEX recording_drafts_target_id_idx ON recording_drafts (target_id);

CREATE UNIQUE INDEX run_leases_active_idx ON run_leases (run_id) WHERE (status = 'ACTIVE');

CREATE INDEX run_leases_holder_idx ON run_leases (holder_worker_id, status);

CREATE INDEX run_leases_reap_idx ON run_leases (status, expires_at) WHERE (status = 'ACTIVE');

CREATE UNIQUE INDEX run_leases_token_idx ON run_leases (run_id, fencing_token);

CREATE INDEX runs_claim_idx ON runs (status, created_at, id);

CREATE UNIQUE INDEX runs_idempotency_idx ON runs (created_by_console_account_id, idempotency_key) WHERE (idempotency_key IS NOT NULL);

CREATE INDEX scenario_drafts_updated_at_idx ON scenario_drafts (updated_at);

CREATE UNIQUE INDEX scenario_versions_scenario_no_idx ON scenario_versions (scenario_id, version_no);

CREATE UNIQUE INDEX scenario_versions_trial_digest_idx ON scenario_versions (scenario_id, source_digest) WHERE (kind = 'trial');

CREATE INDEX scenarios_target_id_idx ON scenarios (target_id);

CREATE UNIQUE INDEX scenarios_target_name_idx ON scenarios (target_id, name);

CREATE UNIQUE INDEX session_leases_active_idx ON session_leases (session_id) WHERE (status = 'ACTIVE');

CREATE INDEX session_leases_holder_idx ON session_leases (holder_worker_id, status);

CREATE INDEX session_leases_reap_idx ON session_leases (status, expires_at) WHERE (status = 'ACTIVE');

CREATE INDEX session_leases_run_id_idx ON session_leases (run_id);

CREATE UNIQUE INDEX step_runs_run_ordinal_idx ON step_runs (run_id, ordinal);

CREATE UNIQUE INDEX step_runs_run_step_idx ON step_runs (run_id, step_id);

CREATE UNIQUE INDEX stored_objects_object_key_idx ON stored_objects (object_key);

CREATE INDEX stored_objects_pending_idx ON stored_objects (status, created_at);

CREATE INDEX stored_objects_purge_idx ON stored_objects (status, purge_attempts, retain_until);

CREATE INDEX stored_objects_run_id_idx ON stored_objects (run_id);

CREATE UNIQUE INDEX target_accounts_id_target_id_idx ON target_accounts (id, target_id);

CREATE INDEX target_accounts_target_id_idx ON target_accounts (target_id);

CREATE UNIQUE INDEX target_accounts_target_username_idx ON target_accounts (target_id, username);

CREATE UNIQUE INDEX targets_code_idx ON targets (code);

INSERT INTO "console_roles" ("id", "key", "name", "description", "kind", "created_at", "updated_at") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'admin', 'Administrator', 'Full access, including identity and permission management.', 'system', '2026-09-13T09:47:09.309Z', '2026-09-13T09:47:09.309Z');

INSERT INTO "console_roles" ("id", "key", "name", "description", "kind", "created_at", "updated_at") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'operator', 'Operator', 'Run and edit workflows. Cannot manage accounts or roles.', 'system', '2026-09-13T09:47:09.309Z', '2026-09-13T09:47:09.309Z');

INSERT INTO "console_roles" ("id", "key", "name", "description", "kind", "created_at", "updated_at") VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'viewer', 'Viewer', 'Read-only access to the console.', 'system', '2026-09-13T09:47:09.309Z', '2026-09-13T09:47:09.309Z');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'audit:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'settings:write');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'settings:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'target:delete');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'target:write');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'target:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'run:cancel');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'run:execute');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'run:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'workflow:delete');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'workflow:write');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'workflow:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'role:delete');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'role:write');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'role:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'account:delete');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'account:write');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'account:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'audit:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'settings:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'target:delete');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'target:write');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'target:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'run:cancel');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'run:execute');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'run:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'workflow:delete');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'workflow:write');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'workflow:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'role:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'account:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'audit:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'settings:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'target:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'run:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'workflow:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'role:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'account:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'session:dispose');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'session:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'session:dispose');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'session:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'session:read');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'run:review');

INSERT INTO "console_role_permissions" ("console_role_id", "permission") VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'run:review');

CREATE TRIGGER scenario_versions_immutable BEFORE UPDATE ON scenario_versions WHEN OLD.definition IS NOT NEW.definition OR OLD.version_no IS NOT NEW.version_no OR OLD.scenario_id IS NOT NEW.scenario_id OR OLD.kind IS NOT NEW.kind OR OLD.compiler_version IS NOT NEW.compiler_version OR OLD.source_digest IS NOT NEW.source_digest BEGIN SELECT RAISE(ABORT, 'scenario_versions immutable'); END;

CREATE TRIGGER runs_snapshot_immutable BEFORE UPDATE ON runs WHEN OLD.snapshot IS NOT NEW.snapshot OR OLD.snapshot_digest IS NOT NEW.snapshot_digest OR OLD.target_id IS NOT NEW.target_id OR OLD.scenario_id IS NOT NEW.scenario_id OR OLD.scenario_version_id IS NOT NEW.scenario_version_id BEGIN SELECT RAISE(ABORT, 'runs immutable'); END;

CREATE TRIGGER attempts_closed_immutable BEFORE UPDATE ON attempts WHEN OLD.status IN ('SUCCEEDED', 'FAILED', 'CANCELLED') AND (OLD.status IS NOT NEW.status OR OLD.output IS NOT NEW.output OR OLD.error IS NOT NEW.error OR OLD.finished_at IS NOT NEW.finished_at) BEGIN SELECT RAISE(ABORT, 'attempts immutable'); END;
