-- 0031 的 SQLite 等价增量：按当前产品目录补齐系统角色权限。只插入缺失行。

INSERT OR IGNORE INTO console_role_permissions (console_role_id, permission)
SELECT r.id, p.permission
FROM console_roles r
JOIN (
  SELECT 'admin' AS role_key, 'account:read' AS permission
  UNION ALL SELECT 'admin', 'account:write'
  UNION ALL SELECT 'admin', 'account:delete'
  UNION ALL SELECT 'admin', 'role:read'
  UNION ALL SELECT 'admin', 'role:write'
  UNION ALL SELECT 'admin', 'role:delete'
  UNION ALL SELECT 'admin', 'workflow:read'
  UNION ALL SELECT 'admin', 'workflow:write'
  UNION ALL SELECT 'admin', 'workflow:delete'
  UNION ALL SELECT 'admin', 'run:read'
  UNION ALL SELECT 'admin', 'run:execute'
  UNION ALL SELECT 'admin', 'run:cancel'
  UNION ALL SELECT 'admin', 'run:review'
  UNION ALL SELECT 'admin', 'run:delete'
  UNION ALL SELECT 'admin', 'session:read'
  UNION ALL SELECT 'admin', 'session:view'
  UNION ALL SELECT 'admin', 'session:control'
  UNION ALL SELECT 'admin', 'session:dispose'
  UNION ALL SELECT 'admin', 'target:read'
  UNION ALL SELECT 'admin', 'target:write'
  UNION ALL SELECT 'admin', 'target:delete'
  UNION ALL SELECT 'admin', 'service:read'
  UNION ALL SELECT 'admin', 'service:write'
  UNION ALL SELECT 'admin', 'settings:read'
  UNION ALL SELECT 'admin', 'settings:write'
  UNION ALL SELECT 'admin', 'audit:read'
  UNION ALL SELECT 'admin', 'audit:login'
  UNION ALL SELECT 'admin', 'ai:execute'
  UNION ALL SELECT 'admin', 'ai:assist'
  UNION ALL SELECT 'admin', 'platform-config:read'
  UNION ALL SELECT 'admin', 'platform-config:write'
  UNION ALL SELECT 'author', 'target:read'
  UNION ALL SELECT 'author', 'target:write'
  UNION ALL SELECT 'author', 'target:delete'
  UNION ALL SELECT 'author', 'workflow:read'
  UNION ALL SELECT 'author', 'workflow:write'
  UNION ALL SELECT 'author', 'workflow:delete'
  UNION ALL SELECT 'author', 'run:read'
  UNION ALL SELECT 'author', 'run:execute'
  UNION ALL SELECT 'author', 'run:cancel'
  UNION ALL SELECT 'author', 'run:review'
  UNION ALL SELECT 'author', 'ai:execute'
  UNION ALL SELECT 'author', 'ai:assist'
  UNION ALL SELECT 'author', 'session:read'
  UNION ALL SELECT 'author', 'session:view'
  UNION ALL SELECT 'author', 'session:control'
  UNION ALL SELECT 'author', 'settings:read'
  UNION ALL SELECT 'operator', 'target:read'
  UNION ALL SELECT 'operator', 'workflow:read'
  UNION ALL SELECT 'operator', 'run:read'
  UNION ALL SELECT 'operator', 'run:execute'
  UNION ALL SELECT 'operator', 'run:cancel'
  UNION ALL SELECT 'operator', 'run:review'
  UNION ALL SELECT 'operator', 'ai:execute'
  UNION ALL SELECT 'operator', 'ai:assist'
  UNION ALL SELECT 'operator', 'session:read'
  UNION ALL SELECT 'operator', 'session:view'
  UNION ALL SELECT 'operator', 'session:control'
  UNION ALL SELECT 'operator', 'session:dispose'
  UNION ALL SELECT 'operator', 'settings:read'
  UNION ALL SELECT 'viewer', 'target:read'
  UNION ALL SELECT 'viewer', 'workflow:read'
  UNION ALL SELECT 'viewer', 'run:read'
  UNION ALL SELECT 'viewer', 'settings:read'
  UNION ALL SELECT 'viewer', 'ai:assist'
) p ON p.role_key = r.key
WHERE r.kind = 'system';
