import assert from 'node:assert/strict'
import { session, sample, artifact, save } from './browser.mjs'
const s = await session()
const checks = []
const check = (name) => { checks.push(name); console.log('PASS', name) }
const order = () => s.page.locator('[data-flow-step]').evaluateAll((elements) => elements.sort((a, b) => Number(a.querySelector('.flowgram-step-body').getAttribute('aria-label').match(/^步骤 (\d+) /)[1]) - Number(b.querySelector('.flowgram-step-body').getAttribute('aria-label').match(/^步骤 (\d+) /)[1])).map((element) => element.getAttribute('data-flow-step')))
const waitOrder = async (expected) => {
  await s.page.waitForFunction((expected) => JSON.stringify([...document.querySelectorAll('[data-flow-step]')].sort((a,b) => Number(a.querySelector('.flowgram-step-body').getAttribute('aria-label').match(/^步骤 (\d+) /)[1]) - Number(b.querySelector('.flowgram-step-body').getAttribute('aria-label').match(/^步骤 (\d+) /)[1])).map((e) => e.getAttribute('data-flow-step'))) === JSON.stringify(expected), expected, { timeout: 5000 })
}
try {
  const original = await s.request(`/scenarios/${sample.scenarioId}`)
  await s.page.goto(sample.url)
  await s.page.locator('[data-flow-step]').first().waitFor()
  assert.equal(await s.page.locator('[data-flow-step]').count(), 10)
  assert.deepEqual(await order(), original.draft.document.steps.map((step) => step.id))
  check('10 步投影与平台 Step ID 一致')
  await s.page.screenshot({ path: artifact('editor-desktop.png'), fullPage: true })
  const handle = s.page.getByRole('button', { name: `拖动步骤 1 ${sample.steps[0].name}`, exact: true })
  const target = s.page.getByRole('button', { name: `在${sample.steps[1].name}后插入步骤`, exact: true })
  const a = await handle.boundingBox(), b = await target.boundingBox()
  console.log('DRAG', a, b)
  await s.page.mouse.move(a.x + a.width / 2, a.y + a.height / 2)
  await s.page.mouse.down()
  await s.page.mouse.move(a.x + a.width / 2 + 15, a.y + a.height / 2 + 20, { steps: 5 })
  await s.page.mouse.move(b.x + b.width / 2, b.y + b.height / 2, { steps: 20 })
  await s.page.waitForTimeout(400)
  await s.page.screenshot({ path: artifact('drag-preview.png'), fullPage: true })
  await s.page.mouse.up()
  await s.page.waitForTimeout(500)
  assert.deepEqual((await order()).slice(0, 2), [sample.steps[1].id, sample.steps[0].id])
  check('真实鼠标拖动修改结构顺序')
  await s.page.getByRole('button', { name: '撤销结构操作', exact: true }).click()
  await waitOrder(sample.steps.map((step) => step.id))
  check('原有结构撤销恢复完整顺序')
  await s.page.getByRole('button', { name: `在${sample.steps[0].name}后插入步骤`, exact: true }).click()
  await s.page.getByRole('menuitem', { name: '断言', exact: true }).click()
  await s.page.waitForFunction(() => document.querySelectorAll('[data-flow-step]').length === 11)
  assert.equal(await s.page.locator('[data-flow-step]').count(), 11)
  assert.equal((await order())[0], sample.steps[0].id)
  check('连线加号调用原有类型菜单并插入第 2 步')
  await s.page.getByRole('button', { name: '撤销结构操作', exact: true }).click()
  await waitOrder(sample.steps.map((step) => step.id))
  assert.equal(await s.page.locator('[data-flow-step]').count(), 10)
  await s.page.getByRole('button', { name: '步骤列表', exact: true }).click()
  await s.page.getByRole('button', { name: /AI 提取订单号与应付金额/ }).first().click()
  await s.page.getByRole('button', { name: '流程画布', exact: true }).click()
  await s.page.locator('[data-flow-step]').first().waitFor()
  await s.page.getByRole('button', { name: '下移', exact: true }).click()
  await s.page.waitForTimeout(300)
  assert.equal(await s.page.getByRole('button', { name: '试跑', exact: true }).isDisabled(), true)
  assert.ok(await s.page.locator('[data-flow-step] [title="引用 / 字段异常"]').count() > 0)
  check('重排导致前向引用时，画布显示诊断并阻止试跑')
  await s.page.getByRole('button', { name: '撤销结构操作', exact: true }).click()
  await s.page.getByLabel('步骤名称', { exact: true }).fill(sample.steps[4].name + ' · 保存验证')
  const saved = s.page.waitForResponse((r) => r.url().endsWith(`/scenarios/${sample.scenarioId}/draft`) && r.request().method() === 'POST')
  await s.page.getByRole('button', { name: '保存草稿', exact: true }).click()
  assert.equal((await saved).status(), 200)
  const changed = await s.request(`/scenarios/${sample.scenarioId}`)
  assert.equal(changed.draft.document.steps[4].name, sample.steps[4].name + ' · 保存验证')
  await s.page.reload()
  await s.page.locator('[data-flow-step]').first().waitFor()
  await waitOrder(sample.steps.map((step) => step.id))
  check('属性编辑经真实 API 保存、刷新后字段与 Step ID 保留')
  // Restore only this sample's tested name using optimistic revision.
  const restored = await s.request(`/scenarios/${sample.scenarioId}/draft`, { revision: changed.draft.revision, document: original.draft.document })
  assert.ok(restored.draft.revision > original.draft.revision)
  await s.page.reload()
  await s.page.locator('[data-flow-step]').first().waitFor()
  await s.page.getByRole('button', { name: '查看全流程', exact: true }).click()
  await s.page.waitForTimeout(400)
  await s.page.screenshot({ path: artifact('editor-overview.png'), fullPage: true })
  assert.deepEqual(s.errors, [])
  check('视图切换、反复挂载无页面异常')
  await save('editor-checks.json', { checks, errors: s.errors, restoredRevision: restored.draft.revision })
} catch (error) {
  await s.page.screenshot({ path: artifact('editor-failure.png'), fullPage: true })
  console.log((await s.page.locator('body').innerText()).slice(-7000))
  await save('editor-checks.json', { checks, errors: s.errors, failure: error.message })
  throw error
} finally { await s.browser.close() }
