import { CANDIDATE_GROUPS_PROTOCOL, MODULE_MANIFEST_PROTOCOL, OUTCOME_MANIFEST_PROTOCOL, RUNTIME_INVARIANT_MANIFEST_PROTOCOL, SESSION_OCCUPANCY_PROTOCOL } from '@cairn/shared'

/** 测试 Worker 登记：占用协议是硬门槛，模块清单能力覆盖 AM-B 领取。 */
export const WORKER_TEST_PROTOCOLS = [
  SESSION_OCCUPANCY_PROTOCOL,
  MODULE_MANIFEST_PROTOCOL,
  CANDIDATE_GROUPS_PROTOCOL,
  OUTCOME_MANIFEST_PROTOCOL,
  RUNTIME_INVARIANT_MANIFEST_PROTOCOL,
] as const
