import {
  AI_TASK_EVIDENCE_PROTOCOL,
  CANDIDATE_GROUPS_PROTOCOL,
  LIST_OUTPUT_PROTOCOL,
  MODULE_MANIFEST_PROTOCOL,
  OUTCOME_MANIFEST_PROTOCOL,
  RESOLUTION_PROTOCOL,
  LOCATOR_RESOLUTION_PROTOCOL,
  RUNTIME_INVARIANT_MANIFEST_PROTOCOL,
  SESSION_OCCUPANCY_PROTOCOL,
  CONTROL_FLOW_PROTOCOL,
  CONTROL_FLOW_PROTOCOL_V2,
} from '@cairn/shared'

/** 测试 Worker 登记：占用协议是硬门槛，模块清单能力覆盖 AM-B 领取。 */
export const WORKER_TEST_PROTOCOLS = [
  SESSION_OCCUPANCY_PROTOCOL,
  AI_TASK_EVIDENCE_PROTOCOL,
  MODULE_MANIFEST_PROTOCOL,
  CANDIDATE_GROUPS_PROTOCOL,
  OUTCOME_MANIFEST_PROTOCOL,
  LIST_OUTPUT_PROTOCOL,
  RUNTIME_INVARIANT_MANIFEST_PROTOCOL,
  RESOLUTION_PROTOCOL,
  LOCATOR_RESOLUTION_PROTOCOL,
  CONTROL_FLOW_PROTOCOL,
  CONTROL_FLOW_PROTOCOL_V2,
] as const
