/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedActionModulesIndexRouteImport } from './routes/_authenticated/action-modules/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedAuditLoginsRouteImport } from './routes/_authenticated/audit/logins'
import { Route as AuthenticatedAuditOperationsRouteImport } from './routes/_authenticated/audit/operations'
import { Route as AuthenticatedPlatformConfigIndexRouteImport } from './routes/_authenticated/platform-config/index'
import { Route as AuthenticatedRecordingsIndexRouteImport } from './routes/_authenticated/recordings/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedRunsIndexRouteImport } from './routes/_authenticated/runs/index'
import { Route as AuthenticatedScenariosIndexRouteImport } from './routes/_authenticated/scenarios/index'
import { Route as AuthenticatedSchedulesIndexRouteImport } from './routes/_authenticated/schedules/index'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services/index'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedTargetsIndexRouteImport } from './routes/_authenticated/targets/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedWorkersIndexRouteImport } from './routes/_authenticated/workers/index'
import { Route as AuthenticatedActionModulesModuleIdIndexRouteImport } from './routes/_authenticated/action-modules/$moduleId/index'
import { Route as AuthenticatedRecordingsRecordingIdIndexRouteImport } from './routes/_authenticated/recordings/$recordingId/index'
import { Route as AuthenticatedRunsRunIdIndexRouteImport } from './routes/_authenticated/runs/$runId/index'
import { Route as AuthenticatedScenariosScenarioIdIndexRouteImport } from './routes/_authenticated/scenarios/$scenarioId/index'
import { Route as AuthenticatedSessionsTargetIdIndexRouteImport } from './routes/_authenticated/sessions/$targetId/index'
import { Route as AuthenticatedTargetsTargetIdIndexRouteImport } from './routes/_authenticated/targets/$targetId/index'
import { Route as AuthenticatedWorkersWorkerIdIndexRouteImport } from './routes/_authenticated/workers/$workerId/index'
import { Route as AuthenticatedSessionsTargetIdAccountIdIndexRouteImport } from './routes/_authenticated/sessions/$targetId/$accountId/index'
import { Route as AuthenticatedTargetsTargetIdMapIndexRouteImport } from './routes/_authenticated/targets/$targetId/map/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActionModulesIndexRoute =
  AuthenticatedActionModulesIndexRouteImport.update({
    id: '/action-modules/',
    path: '/action-modules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLoginsRoute =
  AuthenticatedAuditLoginsRouteImport.update({
    id: '/audit/logins',
    path: '/audit/logins',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditOperationsRoute =
  AuthenticatedAuditOperationsRouteImport.update({
    id: '/audit/operations',
    path: '/audit/operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformConfigIndexRoute =
  AuthenticatedPlatformConfigIndexRouteImport.update({
    id: '/platform-config/',
    path: '/platform-config/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecordingsIndexRoute =
  AuthenticatedRecordingsIndexRouteImport.update({
    id: '/recordings/',
    path: '/recordings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunsIndexRoute = AuthenticatedRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScenariosIndexRoute =
  AuthenticatedScenariosIndexRouteImport.update({
    id: '/scenarios/',
    path: '/scenarios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulesIndexRoute =
  AuthenticatedSchedulesIndexRouteImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedTargetsIndexRoute =
  AuthenticatedTargetsIndexRouteImport.update({
    id: '/targets/',
    path: '/targets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkersIndexRoute =
  AuthenticatedWorkersIndexRouteImport.update({
    id: '/workers/',
    path: '/workers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActionModulesModuleIdIndexRoute =
  AuthenticatedActionModulesModuleIdIndexRouteImport.update({
    id: '/action-modules/$moduleId/',
    path: '/action-modules/$moduleId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecordingsRecordingIdIndexRoute =
  AuthenticatedRecordingsRecordingIdIndexRouteImport.update({
    id: '/recordings/$recordingId/',
    path: '/recordings/$recordingId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRunsRunIdIndexRoute =
  AuthenticatedRunsRunIdIndexRouteImport.update({
    id: '/runs/$runId/',
    path: '/runs/$runId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScenariosScenarioIdIndexRoute =
  AuthenticatedScenariosScenarioIdIndexRouteImport.update({
    id: '/scenarios/$scenarioId/',
    path: '/scenarios/$scenarioId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsTargetIdIndexRoute =
  AuthenticatedSessionsTargetIdIndexRouteImport.update({
    id: '/sessions/$targetId/',
    path: '/sessions/$targetId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTargetsTargetIdIndexRoute =
  AuthenticatedTargetsTargetIdIndexRouteImport.update({
    id: '/targets/$targetId/',
    path: '/targets/$targetId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkersWorkerIdIndexRoute =
  AuthenticatedWorkersWorkerIdIndexRouteImport.update({
    id: '/workers/$workerId/',
    path: '/workers/$workerId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsTargetIdAccountIdIndexRoute =
  AuthenticatedSessionsTargetIdAccountIdIndexRouteImport.update({
    id: '/sessions/$targetId/$accountId/',
    path: '/sessions/$targetId/$accountId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTargetsTargetIdMapIndexRoute =
  AuthenticatedTargetsTargetIdMapIndexRouteImport.update({
    id: '/targets/$targetId/map/',
    path: '/targets/$targetId/map/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/audit/logins': typeof AuthenticatedAuditLoginsRoute
  '/audit/operations': typeof AuthenticatedAuditOperationsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/action-modules/': typeof AuthenticatedActionModulesIndexRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/platform-config/': typeof AuthenticatedPlatformConfigIndexRoute
  '/recordings/': typeof AuthenticatedRecordingsIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/runs/': typeof AuthenticatedRunsIndexRoute
  '/scenarios/': typeof AuthenticatedScenariosIndexRoute
  '/schedules/': typeof AuthenticatedSchedulesIndexRoute
  '/services/': typeof AuthenticatedServicesIndexRoute
  '/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/targets/': typeof AuthenticatedTargetsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/workers/': typeof AuthenticatedWorkersIndexRoute
  '/action-modules/$moduleId/': typeof AuthenticatedActionModulesModuleIdIndexRoute
  '/recordings/$recordingId/': typeof AuthenticatedRecordingsRecordingIdIndexRoute
  '/runs/$runId/': typeof AuthenticatedRunsRunIdIndexRoute
  '/scenarios/$scenarioId/': typeof AuthenticatedScenariosScenarioIdIndexRoute
  '/sessions/$targetId/': typeof AuthenticatedSessionsTargetIdIndexRoute
  '/targets/$targetId/': typeof AuthenticatedTargetsTargetIdIndexRoute
  '/workers/$workerId/': typeof AuthenticatedWorkersWorkerIdIndexRoute
  '/sessions/$targetId/$accountId/': typeof AuthenticatedSessionsTargetIdAccountIdIndexRoute
  '/targets/$targetId/map/': typeof AuthenticatedTargetsTargetIdMapIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/audit/logins': typeof AuthenticatedAuditLoginsRoute
  '/audit/operations': typeof AuthenticatedAuditOperationsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/action-modules': typeof AuthenticatedActionModulesIndexRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/platform-config': typeof AuthenticatedPlatformConfigIndexRoute
  '/recordings': typeof AuthenticatedRecordingsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/runs': typeof AuthenticatedRunsIndexRoute
  '/scenarios': typeof AuthenticatedScenariosIndexRoute
  '/schedules': typeof AuthenticatedSchedulesIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/targets': typeof AuthenticatedTargetsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workers': typeof AuthenticatedWorkersIndexRoute
  '/action-modules/$moduleId': typeof AuthenticatedActionModulesModuleIdIndexRoute
  '/recordings/$recordingId': typeof AuthenticatedRecordingsRecordingIdIndexRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdIndexRoute
  '/scenarios/$scenarioId': typeof AuthenticatedScenariosScenarioIdIndexRoute
  '/sessions/$targetId': typeof AuthenticatedSessionsTargetIdIndexRoute
  '/targets/$targetId': typeof AuthenticatedTargetsTargetIdIndexRoute
  '/workers/$workerId': typeof AuthenticatedWorkersWorkerIdIndexRoute
  '/sessions/$targetId/$accountId': typeof AuthenticatedSessionsTargetIdAccountIdIndexRoute
  '/targets/$targetId/map': typeof AuthenticatedTargetsTargetIdMapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/audit/logins': typeof AuthenticatedAuditLoginsRoute
  '/_authenticated/audit/operations': typeof AuthenticatedAuditOperationsRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/action-modules/': typeof AuthenticatedActionModulesIndexRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/platform-config/': typeof AuthenticatedPlatformConfigIndexRoute
  '/_authenticated/recordings/': typeof AuthenticatedRecordingsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/runs/': typeof AuthenticatedRunsIndexRoute
  '/_authenticated/scenarios/': typeof AuthenticatedScenariosIndexRoute
  '/_authenticated/schedules/': typeof AuthenticatedSchedulesIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/targets/': typeof AuthenticatedTargetsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/workers/': typeof AuthenticatedWorkersIndexRoute
  '/_authenticated/action-modules/$moduleId/': typeof AuthenticatedActionModulesModuleIdIndexRoute
  '/_authenticated/recordings/$recordingId/': typeof AuthenticatedRecordingsRecordingIdIndexRoute
  '/_authenticated/runs/$runId/': typeof AuthenticatedRunsRunIdIndexRoute
  '/_authenticated/scenarios/$scenarioId/': typeof AuthenticatedScenariosScenarioIdIndexRoute
  '/_authenticated/sessions/$targetId/': typeof AuthenticatedSessionsTargetIdIndexRoute
  '/_authenticated/targets/$targetId/': typeof AuthenticatedTargetsTargetIdIndexRoute
  '/_authenticated/workers/$workerId/': typeof AuthenticatedWorkersWorkerIdIndexRoute
  '/_authenticated/sessions/$targetId/$accountId/': typeof AuthenticatedSessionsTargetIdAccountIdIndexRoute
  '/_authenticated/targets/$targetId/map/': typeof AuthenticatedTargetsTargetIdMapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/audit/logins'
    | '/audit/operations'
    | '/settings/account'
    | '/settings/appearance'
    | '/action-modules/'
    | '/audit/'
    | '/platform-config/'
    | '/recordings/'
    | '/roles/'
    | '/runs/'
    | '/scenarios/'
    | '/schedules/'
    | '/services/'
    | '/sessions/'
    | '/settings/'
    | '/targets/'
    | '/users/'
    | '/workers/'
    | '/action-modules/$moduleId/'
    | '/recordings/$recordingId/'
    | '/runs/$runId/'
    | '/scenarios/$scenarioId/'
    | '/sessions/$targetId/'
    | '/targets/$targetId/'
    | '/workers/$workerId/'
    | '/sessions/$targetId/$accountId/'
    | '/targets/$targetId/map/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/audit/logins'
    | '/audit/operations'
    | '/settings/account'
    | '/settings/appearance'
    | '/action-modules'
    | '/audit'
    | '/platform-config'
    | '/recordings'
    | '/roles'
    | '/runs'
    | '/scenarios'
    | '/schedules'
    | '/services'
    | '/sessions'
    | '/settings'
    | '/targets'
    | '/users'
    | '/workers'
    | '/action-modules/$moduleId'
    | '/recordings/$recordingId'
    | '/runs/$runId'
    | '/scenarios/$scenarioId'
    | '/sessions/$targetId'
    | '/targets/$targetId'
    | '/workers/$workerId'
    | '/sessions/$targetId/$accountId'
    | '/targets/$targetId/map'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/audit/logins'
    | '/_authenticated/audit/operations'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/action-modules/'
    | '/_authenticated/audit/'
    | '/_authenticated/platform-config/'
    | '/_authenticated/recordings/'
    | '/_authenticated/roles/'
    | '/_authenticated/runs/'
    | '/_authenticated/scenarios/'
    | '/_authenticated/schedules/'
    | '/_authenticated/services/'
    | '/_authenticated/sessions/'
    | '/_authenticated/settings/'
    | '/_authenticated/targets/'
    | '/_authenticated/users/'
    | '/_authenticated/workers/'
    | '/_authenticated/action-modules/$moduleId/'
    | '/_authenticated/recordings/$recordingId/'
    | '/_authenticated/runs/$runId/'
    | '/_authenticated/scenarios/$scenarioId/'
    | '/_authenticated/sessions/$targetId/'
    | '/_authenticated/targets/$targetId/'
    | '/_authenticated/workers/$workerId/'
    | '/_authenticated/sessions/$targetId/$accountId/'
    | '/_authenticated/targets/$targetId/map/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/action-modules/': {
      id: '/_authenticated/action-modules/'
      path: '/action-modules'
      fullPath: '/action-modules/'
      preLoaderRoute: typeof AuthenticatedActionModulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/logins': {
      id: '/_authenticated/audit/logins'
      path: '/audit/logins'
      fullPath: '/audit/logins'
      preLoaderRoute: typeof AuthenticatedAuditLoginsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/operations': {
      id: '/_authenticated/audit/operations'
      path: '/audit/operations'
      fullPath: '/audit/operations'
      preLoaderRoute: typeof AuthenticatedAuditOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-config/': {
      id: '/_authenticated/platform-config/'
      path: '/platform-config'
      fullPath: '/platform-config/'
      preLoaderRoute: typeof AuthenticatedPlatformConfigIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recordings/': {
      id: '/_authenticated/recordings/'
      path: '/recordings'
      fullPath: '/recordings/'
      preLoaderRoute: typeof AuthenticatedRecordingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runs/': {
      id: '/_authenticated/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthenticatedRunsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenarios/': {
      id: '/_authenticated/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof AuthenticatedScenariosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules/': {
      id: '/_authenticated/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof AuthenticatedSchedulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/targets/': {
      id: '/_authenticated/targets/'
      path: '/targets'
      fullPath: '/targets/'
      preLoaderRoute: typeof AuthenticatedTargetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers/': {
      id: '/_authenticated/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof AuthenticatedWorkersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/action-modules/$moduleId/': {
      id: '/_authenticated/action-modules/$moduleId/'
      path: '/action-modules/$moduleId'
      fullPath: '/action-modules/$moduleId/'
      preLoaderRoute: typeof AuthenticatedActionModulesModuleIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recordings/$recordingId/': {
      id: '/_authenticated/recordings/$recordingId/'
      path: '/recordings/$recordingId'
      fullPath: '/recordings/$recordingId/'
      preLoaderRoute: typeof AuthenticatedRecordingsRecordingIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runs/$runId/': {
      id: '/_authenticated/runs/$runId/'
      path: '/runs/$runId'
      fullPath: '/runs/$runId/'
      preLoaderRoute: typeof AuthenticatedRunsRunIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenarios/$scenarioId/': {
      id: '/_authenticated/scenarios/$scenarioId/'
      path: '/scenarios/$scenarioId'
      fullPath: '/scenarios/$scenarioId/'
      preLoaderRoute: typeof AuthenticatedScenariosScenarioIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$targetId/': {
      id: '/_authenticated/sessions/$targetId/'
      path: '/sessions/$targetId'
      fullPath: '/sessions/$targetId/'
      preLoaderRoute: typeof AuthenticatedSessionsTargetIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/targets/$targetId/': {
      id: '/_authenticated/targets/$targetId/'
      path: '/targets/$targetId'
      fullPath: '/targets/$targetId/'
      preLoaderRoute: typeof AuthenticatedTargetsTargetIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workers/$workerId/': {
      id: '/_authenticated/workers/$workerId/'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId/'
      preLoaderRoute: typeof AuthenticatedWorkersWorkerIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$targetId/$accountId/': {
      id: '/_authenticated/sessions/$targetId/$accountId/'
      path: '/sessions/$targetId/$accountId'
      fullPath: '/sessions/$targetId/$accountId/'
      preLoaderRoute: typeof AuthenticatedSessionsTargetIdAccountIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/targets/$targetId/map/': {
      id: '/_authenticated/targets/$targetId/map/'
      path: '/targets/$targetId/map'
      fullPath: '/targets/$targetId/map/'
      preLoaderRoute: typeof AuthenticatedTargetsTargetIdMapIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAuditLoginsRoute: typeof AuthenticatedAuditLoginsRoute
  AuthenticatedAuditOperationsRoute: typeof AuthenticatedAuditOperationsRoute
  AuthenticatedActionModulesIndexRoute: typeof AuthenticatedActionModulesIndexRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedPlatformConfigIndexRoute: typeof AuthenticatedPlatformConfigIndexRoute
  AuthenticatedRecordingsIndexRoute: typeof AuthenticatedRecordingsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedRunsIndexRoute: typeof AuthenticatedRunsIndexRoute
  AuthenticatedScenariosIndexRoute: typeof AuthenticatedScenariosIndexRoute
  AuthenticatedSchedulesIndexRoute: typeof AuthenticatedSchedulesIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
  AuthenticatedTargetsIndexRoute: typeof AuthenticatedTargetsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWorkersIndexRoute: typeof AuthenticatedWorkersIndexRoute
  AuthenticatedActionModulesModuleIdIndexRoute: typeof AuthenticatedActionModulesModuleIdIndexRoute
  AuthenticatedRecordingsRecordingIdIndexRoute: typeof AuthenticatedRecordingsRecordingIdIndexRoute
  AuthenticatedRunsRunIdIndexRoute: typeof AuthenticatedRunsRunIdIndexRoute
  AuthenticatedScenariosScenarioIdIndexRoute: typeof AuthenticatedScenariosScenarioIdIndexRoute
  AuthenticatedSessionsTargetIdIndexRoute: typeof AuthenticatedSessionsTargetIdIndexRoute
  AuthenticatedTargetsTargetIdIndexRoute: typeof AuthenticatedTargetsTargetIdIndexRoute
  AuthenticatedWorkersWorkerIdIndexRoute: typeof AuthenticatedWorkersWorkerIdIndexRoute
  AuthenticatedSessionsTargetIdAccountIdIndexRoute: typeof AuthenticatedSessionsTargetIdAccountIdIndexRoute
  AuthenticatedTargetsTargetIdMapIndexRoute: typeof AuthenticatedTargetsTargetIdMapIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAuditLoginsRoute: AuthenticatedAuditLoginsRoute,
  AuthenticatedAuditOperationsRoute: AuthenticatedAuditOperationsRoute,
  AuthenticatedActionModulesIndexRoute: AuthenticatedActionModulesIndexRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedPlatformConfigIndexRoute: AuthenticatedPlatformConfigIndexRoute,
  AuthenticatedRecordingsIndexRoute: AuthenticatedRecordingsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedRunsIndexRoute: AuthenticatedRunsIndexRoute,
  AuthenticatedScenariosIndexRoute: AuthenticatedScenariosIndexRoute,
  AuthenticatedSchedulesIndexRoute: AuthenticatedSchedulesIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
  AuthenticatedTargetsIndexRoute: AuthenticatedTargetsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWorkersIndexRoute: AuthenticatedWorkersIndexRoute,
  AuthenticatedActionModulesModuleIdIndexRoute:
    AuthenticatedActionModulesModuleIdIndexRoute,
  AuthenticatedRecordingsRecordingIdIndexRoute:
    AuthenticatedRecordingsRecordingIdIndexRoute,
  AuthenticatedRunsRunIdIndexRoute: AuthenticatedRunsRunIdIndexRoute,
  AuthenticatedScenariosScenarioIdIndexRoute:
    AuthenticatedScenariosScenarioIdIndexRoute,
  AuthenticatedSessionsTargetIdIndexRoute:
    AuthenticatedSessionsTargetIdIndexRoute,
  AuthenticatedTargetsTargetIdIndexRoute:
    AuthenticatedTargetsTargetIdIndexRoute,
  AuthenticatedWorkersWorkerIdIndexRoute:
    AuthenticatedWorkersWorkerIdIndexRoute,
  AuthenticatedSessionsTargetIdAccountIdIndexRoute:
    AuthenticatedSessionsTargetIdAccountIdIndexRoute,
  AuthenticatedTargetsTargetIdMapIndexRoute:
    AuthenticatedTargetsTargetIdMapIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
