export {
  SessionDomainError,
  isReusable,
  isClaimable,
  profileKeyFor,
  findLiveSession,
  getSessionById,
  getLeaseById,
  countOpenSessionsForWorker,
  nextGenerationForKey,
  createSession,
  requireCreatedSession,
  findEvictableSession,
  setSessionStatus,
  setSessionProbe,
  setSessionAuthSummary,
  touchSessionUsed,
  claimAuthHold,
  releaseAuthHold,
  acquireSessionLease,
  renewSessionLease,
  releaseSessionLease,
  expireStaleLeases,
  listReapableSessions,
  listRequestedCloseSessions,
  markSessionsClosing,
  markSessionsLostForWorkers,
  revokeWorkerLeases,
  closeWorkerSessions,
  verifySessionLeaseForCommit,
  findActiveLeaseForSession,
  listActiveSessionLeasesForWorker,
  listOwnedLiveSessions,
  listOwnedOpenSessions,
  forceLastUsedAt,
  forceLeaseExpiresAt,
  forceSessionGeneration,
  listExpiredAuthHolds,
  expireAuthHold,
  loadSecretCiphertext,
  registerStandaloneSecret,
  listSessions,
  toSessionDto,
  getSessionDto,
  disposeStuckSession,
  DISPOSABLE_SESSION_STATUSES,
  type SessionKey,
  type SessionRecord,
  type LeaseRecord,
  type LeaseBusyInfo,
  type LeaseOutcome,
  type CreateSessionInput,
  type CreateSessionResult,
} from './sessions.js'
export {
  hashAuthControlToken,
  newAuthControlToken,
  isBoundAuthHold,
  enterRunWaitingForAuth,
  acquireAuthControl,
  heartbeatAuthControl,
  releaseAuthControl,
  expireStaleAuthControl,
  findSessionByAuthHoldRun,
} from './auth-control.js'
export {
  readSessionScheduling,
  lockWorkerRow,
  findActiveLeaseRow,
  findAuthWaitLeaseForRun,
  findAuthWaitLeaseForOperation,
  getSessionOperation,
  markSessionOperationWaitingForAuth,
  getSessionProfile,
  upsertSessionProfile,
  invalidateSessionProfile,
  evaluateRunSessionEligibility,
  computeOccupancyPlacement,
  claimSessionUse,
  transitionSessionUse,
  renewSessionUse,
  releaseSessionUse,
  reapSessionLeases,
  requestSessionOperation,
  claimSessionOperation,
  finishSessionOperation,
  occupancyGrantFromLease,
  contentDigestFor,
  workerHasOccupancyProtocol,
  workerHasMaintenanceProtocol,
  toSessionOperationDto,
  type OccupancyOwner,
  type ClaimSessionUseInput,
  type ClaimSessionUseResult,
  type ClaimedSessionOperation,
  type PlacementFacts,
} from './occupancy.js'
export {
  appendSessionEvent,
  listSessionEvents,
  listSessionEventsAfter,
  requestMaintenanceOperation,
  cancelSessionOperation,
  setSessionRetention,
  adoptSessionRetention,
  scheduleNextAuthCheck,
  listDueRetainedSessions,
  listAccountSessionOverview,
  getAccountSessionDetail,
  countSessionEventWatermark,
} from './maintenance.js'
export {
  readLiveSessionAuth,
  loadAuthProfileRevision,
  loadCurrentAuthProfile,
  freezeAuthVerificationForRun,
  getTargetAuthProfileView,
  publishTargetAuthProfile,
  updateTargetAccountIdentity,
  resetAuthBudgetAfterCredentialChange,
  occupyAutoLoginBudget,
  recordAutoLoginOutcome,
  startAuthProfileValidation,
  getAuthProfileValidation,
  observeAuthProfileValidation,
  listTargetsOutsideFreshnessRange,
  loadAccountAuthDisplay,
  assertLiveAuthConfiguration,
} from './auth-profile.js'

export { assertSessionAccountActive, assertSessionActorPermission, assertMaintenanceAuthorized } from './access.js'

export { recoverSessionOperations, markMaintenanceLoginSubmitted } from './occupancy.js'

export { bindOperationSession } from './occupancy.js'

export { recreateSessionForOperation } from './occupancy.js'
