import { afterEach, describe, expect, it } from 'vitest'
import { eq, inArray } from 'drizzle-orm'
import { LOCAL_SECRET_PROVIDER } from '@cairn/shared'
import { DRIVERS, type ContractDriver, openContractDb } from './contract-fixture.js'
import * as api from '../index.js'
import { expose, connection } from '../database.js'
import { schemaFor } from '../native.js'
import { newId } from '../id.js'
import type { DbHandle } from '../client.js'

describe.each(DRIVERS)('%s 账号凭据管理闭环', (driver: ContractDriver) => {
  const handles: DbHandle[] = []
  afterEach(async () => { for (const h of handles.splice(0)) await h.close() })
  async function setup() {
    const handle = await openContractDb(driver); handles.push(handle)
    const db = expose(handle); const native = connection(db); const tables = schemaFor(native)
    const rbac = new api.RbacStore(db, { hash: async s => s, verify: async (s, h) => s === h })
    const roles = (await rbac.listRoles()).items; const adminRole = roles.find(r => r.key === 'admin')!
    const admin = await rbac.createAccount({ email: 'admin', displayName: '管理员', password: 'test-password', roleIds: [adminRole.id] }, null)
    const targets = new api.TargetsStore(db, (_id, value) => Buffer.from(value))
    const makeTarget = (code: string) => targets.createTarget({ code, name: code, entryUrl: 'https://example.com', loginFields: null, authMethod: 'password', captchaMode: 'none', status: 'active' }, admin)
    const target = await makeTarget('T1')
    const makeAccount = (targetId = target.id, username = '001alice') => targets.createAccount(targetId, { displayName: username, username, password: ' old password ', usage: 'business', status: 'active', validity: { mode: 'days', amount: 60, timeZone: 'UTC', startedAt: '2026-01-31T08:00:00.000Z' } }, admin)
    const account = await makeAccount()
    return { db, native, tables, rbac, roles, admin, targets, target, account, makeTarget, makeAccount }
  }
  it('两个入口单独改有效期保留密码及起算时间，账号改名保持同源', async () => {
    const { db, native, tables, admin, targets, target, account } = await setup()
    const before = await api.getCredential(db, account.id, admin)
    await targets.updateAccount(target.id, account.id, { validity: { mode: 'months', amount: 2, timeZone: 'UTC' }, expectedRevision: before.revision }, admin)
    const after = await api.getCredential(db, account.id, admin)
    expect(after.currentVersionId).toBe(before.currentVersionId)
    expect(after.validityStartedAt).toBe(before.validityStartedAt)
    expect(after.maintenanceDueAt).toBe('2026-03-31T08:00:00.000Z')
    const renamed = await api.updateCredentialMetadata(db, account.id, { expectedRevision: after.revision, name: '新账号名', validity: { mode: 'permanent' } }, admin)
    expect((await targets.getAccount(target.id, account.id)).displayName).toBe('新账号名')
    expect(renamed.maintenanceDueAt).toBeNull()
    expect(await native.select().from(tables.credentialVersions)).toHaveLength(1)
  })
  it('角色各自范围不交叉扩权；来源入口、导入、使用关系与批次失权收敛', async () => {
    const { db, rbac, admin, targets, target, account, makeTarget, makeAccount } = await setup()
    const other = await makeTarget('T2'); const b = await makeAccount(other.id, '001alice')
    const read = await rbac.createRole({ key: 'read_all', name: '全目标只读', permissions: ['target:read', 'credential:read'] }, admin)
    const write = await rbac.createRole({ key: 'write_some', name: '局部维护', permissions: ['credential:read', 'credential:write', 'credential:import', 'credential:delete', 'target:read'] }, admin)
    const operator = await rbac.createAccount({ email: 'operator', displayName: '维护员', password: 'test-password', roleIds: [read.id, write.id], targetScopes: [{ roleId: read.id, mode: 'all', targetIds: [] }, { roleId: write.id, mode: 'selected', targetIds: [target.id] }] }, admin)
    expect((await api.getCredential(db, account.id, operator)).capabilities.canReplace).toBe(true)
    expect((await api.getCredential(db, b.id, operator)).capabilities.canReplace).toBe(false)
    expect((await targets.listTargets({}, operator)).items).toHaveLength(2)
    expect((await targets.listTargets({ credentialAction: 'write' }, operator)).items.map(i => i.id)).toEqual([target.id])
    await expect(targets.updateAccount(other.id, b.id, { password: 'nope', validity: { mode: 'permanent' } }, operator)).rejects.toMatchObject({ code: 'TARGET_NOT_FOUND' })
    await expect(targets.updateAccount(target.id, account.id, { displayName: '不允许修改身份' }, operator)).rejects.toMatchObject({ code: 'TARGET_NOT_FOUND' })
    await targets.updateAccount(target.id, account.id, { validity: { mode: 'permanent' } }, operator)
    const resolved = await api.resolveCredentialImport(db, { version: 1, rows: [{ row: 2, targetCode: 'T1', username: '001alice' }, { row: 3, targetCode: 'T2', username: '001alice' }] }, operator)
    expect(resolved.rows[0]?.item?.id).toBe(account.id)
    expect(resolved.rows[1]?.item).toBeNull()
    expect(resolved.rows[1]?.error).not.toContain('T2')
    expect((await api.listCredentialUsages(db, account.id, operator)).items.map(i => i.resource)).toEqual(['target_account'])
    const batch = await api.createCredentialBatch(db, { source: 'excel', kind: 'password_replace', idempotencyKey: newId(), items: [{ itemId: newId(), credentialId: account.id, expectedRevision: resolved.rows[0]!.item!.revision }] }, operator)
    await rbac.assignAccountRoles(operator.id, { roleIds: [read.id, write.id], targetScopes: [{ roleId: read.id, mode: 'none', targetIds: [] }, { roleId: write.id, mode: 'none', targetIds: [] }] }, admin)
    expect((await targets.listTargets({}, operator)).items).toHaveLength(0)
    expect((await api.listCredentials(db, {}, operator)).stats.visible).toBe(0)
    const hidden = await api.getCredentialBatch(db, batch.batchId, operator)
    expect(hidden.items[0]?.credentialId).toBeNull()
    const result = await api.submitSealedBatchPassword(db, { batchId: batch.batchId, itemId: batch.items[0]!.itemId, idempotencyKey: batch.items[0]!.itemId, requestDigest: 'protected', sealed: { id: newId(), provider: LOCAL_SECRET_PROVIDER, ciphertext: Buffer.from('never saved') }, validity: { mode: 'permanent' }, actor: operator })
    expect(result.items[0]?.status).toBe('failed')
    await expect(rbac.assignAccountRoles(operator.id, { roleIds: [read.id], targetScopes: [{ roleId: read.id, mode: 'all', targetIds: [] }] }, operator)).rejects.toMatchObject({ kind: 'forbidden' })
    await expect(rbac.updateRole(read.id, { permissions: ['target:read', 'credential:write'] }, operator)).rejects.toMatchObject({ kind: 'forbidden' })
  })
  it('匹配严格校验技术标识与业务键、重复全部拒绝且不改变密码', async () => {
    const { db, admin, account, target, makeTarget, makeAccount } = await setup()
    const t2 = await makeTarget('T2'); const b = await makeAccount(t2.id, '001alice')
    const rows = await api.resolveCredentialImport(db, { version: 1, rows: [{ row: 2, credentialId: account.id, targetCode: 'T2', username: '001alice' }, { row: 3, credentialId: b.id, targetId: target.id }, { row: 4, targetCode: 'T1', username: '001alice' }, { row: 5, targetAccountId: account.id, targetId: target.id }] }, admin)
    expect(rows.rows.every(r => r.error)).toBe(true)
    expect(rows.rows.slice(0, 2).every(r => r.item === null)).toBe(true)
    const current = await api.getCredential(db, account.id, admin)
    await expect(api.createCredentialBatch(db, { kind: 'password_replace', idempotencyKey: newId(), items: [{ itemId: newId(), credentialId: account.id, targetId: t2.id, expectedRevision: current.revision }] }, admin)).rejects.toMatchObject({ code: 'CREDENTIAL_BINDING_MISMATCH' })
    expect((await api.getCredential(db, account.id, admin)).revision).toBe(current.revision)
  })
  it('会话列表与 SSE 按同一目标授权过滤，撤权后既有订阅也不再返回事件', async () => {
    const { db, rbac, admin, target, account, makeTarget, makeAccount } = await setup()
    const other = await makeTarget('T2'); const otherAccount = await makeAccount(other.id)
    const role = await rbac.createRole({ key: 'session_reader', name: '会话查看', permissions: ['target:read', 'session:read'] }, admin)
    const reader = await rbac.createAccount({ email: 'session-reader', displayName: '会话查看者', password: 'test-password', roleIds: [role.id], targetScopes: [{ roleId: role.id, mode: 'selected', targetIds: [target.id] }] }, admin)
    for (const key of [{ targetId: target.id, targetAccountId: account.id }, { targetId: other.id, targetAccountId: otherAccount.id }]) await api.appendSessionEvent(db, { key, type: 'auth.unknown' })
    expect((await api.listAccountSessionOverview(db, {}, reader.id)).items.map(i => i.targetId)).toEqual([target.id])
    expect((await api.listSessionEventsAfter(db, {}, reader.id)).map(i => i.targetId)).toEqual([target.id])
    await expect(api.authorizeTargetRequest(db, reader.id, { targetId: other.id, permissions: ['session:read'] })).rejects.toMatchObject({ code: 'TARGET_NOT_FOUND' })
    await rbac.assignAccountRoles(reader.id, { roleIds: [role.id], targetScopes: [{ roleId: role.id, mode: 'none', targetIds: [] }] }, admin)
    expect(await api.listSessionEventsAfter(db, {}, reader.id)).toEqual([])
    expect((await api.listAccountSessionOverview(db, {}, reader.id)).items).toEqual([])
  })
  it('同键并发只写一版，错误与冲突不留下孤立密文，200 回执报告失败', async () => {
    const { db, native, tables, admin, account } = await setup()
    const current = await api.getCredential(db, account.id, admin)
    const body = { kind: 'password_replace' as const, idempotencyKey: newId(), items: [{ itemId: newId(), credentialId: account.id, expectedRevision: current.revision }] }
    const [batch, repeat] = await Promise.all([api.createCredentialBatch(db, body, admin), api.createCredentialBatch(db, body, admin)])
    expect(repeat.batchId).toBe(batch.batchId)
    const a = newId(), b = newId()
    const submit = (id: string, digest = 'protected-same', validity = { mode: 'permanent' as const }) => api.submitSealedBatchPassword(db, { batchId: batch.batchId, itemId: body.items[0]!.itemId, idempotencyKey: body.items[0]!.itemId, requestDigest: digest, sealed: { id, provider: LOCAL_SECRET_PROVIDER, ciphertext: Buffer.from(' new 密码 ') }, validity, actor: admin })
    const receipts = await Promise.all([submit(a), submit(b)])
    expect(receipts.every(r => r.items[0]?.status === 'succeeded')).toBe(true)
    expect(await native.select().from(tables.secrets).where(inArray(tables.secrets.id, [a, b]))).toHaveLength(1)
    await expect(submit(newId(), 'different-content')).rejects.toMatchObject({ code: 'CREDENTIAL_IDEMPOTENCY_CONFLICT' })
    await expect(api.createCredentialBatch(db, { ...body, items: [{ ...body.items[0]!, expectedRevision: current.revision + 1 }] }, admin)).rejects.toMatchObject({ code: 'CREDENTIAL_IDEMPOTENCY_CONFLICT' })
    const latest = await api.getCredential(db, account.id, admin)
    const failedBatch = await api.createCredentialBatch(db, { ...body, idempotencyKey: newId(), items: [{ ...body.items[0]!, itemId: newId(), expectedRevision: latest.revision }] }, admin)
    const invalidSecret = newId()
    const failed = await api.submitSealedBatchPassword(db, { batchId: failedBatch.batchId, itemId: failedBatch.items[0]!.itemId, idempotencyKey: failedBatch.items[0]!.itemId, requestDigest: 'future-invalid', sealed: { id: invalidSecret, provider: LOCAL_SECRET_PROVIDER, ciphertext: Buffer.from('should rollback') }, validity: { mode: 'days', amount: 60, timeZone: 'UTC', startedAt: '2099-01-01T00:00:00.000Z' }, actor: admin })
    expect(failed.items[0]?.status).toBe('failed')
    expect(await native.select().from(tables.secrets).where(eq(tables.secrets.id, invalidSecret))).toHaveLength(0)
    expect((await api.getCredential(db, account.id, admin)).revision).toBe(latest.revision)
    expect((await api.getCredential(db, account.id, admin)).currentVersionId).toBe(latest.currentVersionId)
  })
  it('清除与删除登记保留目标账号，重新录入才恢复且无重复账号', async () => {
    const { db, native, tables, admin, targets, target, account } = await setup()
    let item = await api.getCredential(db, account.id, admin)
    await api.clearCredential(db, item.id, { expectedRevision: item.revision }, admin)
    expect((await targets.getAccount(target.id, account.id)).hasPassword).toBe(false)
    item = await api.getCredential(db, account.id, admin)
    await api.clearCredential(db, item.id, { expectedRevision: item.revision }, admin, true)
    expect((await api.listCredentials(db, {}, admin)).items).toHaveLength(0)
    expect((await api.listCredentialHistory(db, item.id, {}, admin)).items.length).toBeGreaterThan(0)
    await targets.updateAccount(target.id, account.id, { displayName: '仍在的账号' }, admin)
    expect((await api.listCredentials(db, {}, admin)).items).toHaveLength(0)
    await targets.updateAccount(target.id, account.id, { password: 'restored', validity: { mode: 'permanent' } }, admin)
    expect((await api.getCredential(db, account.id, admin)).hasPassword).toBe(true)
    expect(await native.select().from(tables.targetAccounts)).toHaveLength(1)
    expect(await native.select().from(tables.credentials)).toHaveLength(1)
  })
  it('超过 200 条目录先聚合后分页，导入可匹配末页账号', async () => {
    const { db, native, tables, admin, target } = await setup()
    const ids = Array.from({ length: 210 }, () => newId())
    const now = new Date('2025-01-01T00:00:00.000Z')
    await native.insert(tables.targetAccounts).values(ids.map((id, i) => ({ id, targetId: target.id, displayName: `账号 ${i}`, username: `bulk-${i}`, usage: 'business' as const, status: 'active' as const, createdAt: now, updatedAt: now })))
    await native.insert(tables.credentials).values(ids.map(id => ({ id, type: 'target_password' as const, source: 'target_account' as const, name: '占位', tags: [], createdAt: now, updatedAt: now })))
    await native.insert(tables.credentialBindings).values(ids.map(id => ({ id, credentialId: id, kind: 'target_account', targetId: target.id, targetAccountId: id, identityUsername: 'bulk', createdAt: now, updatedAt: now })))
    await native.insert(tables.credentialMaintenancePolicies).values(ids.map(id => ({ credentialId: id, mode: 'unknown' as const, updatedAt: now })))
    let page = await api.listCredentials(db, { limit: 100 }, admin)
    expect(page.stats.visible).toBe(211)
    expect(page.stats.unknown).toBe(210)
    const firstIds = new Set(page.items.map(i => i.id)); const last = ids.find(id => !firstIds.has(id))!
    const match = await api.resolveCredentialImport(db, { version: 1, rows: [{ row: 2, credentialId: last, targetCode: 'T1', username: `bulk-${ids.indexOf(last)}` }] }, admin)
    expect(match.rows[0]?.item?.id).toBe(last)
    const all = [...page.items]
    while (page.nextCursor) { page = await api.listCredentials(db, { limit: 100, cursor: page.nextCursor }, admin); all.push(...page.items) }
    expect(new Set(all.map(i => i.id)).size).toBe(211)
  })
  it('正在使用的账号不能清除或删除，凭据和来源两入口均拒绝', async () => {
    const { db, native, tables, admin, target, account, targets } = await setup()
    const sessionId = newId(); const now = new Date()
    await native.insert(tables.browserSessions).values({ id: sessionId, targetId: target.id, targetAccountId: account.id, status: 'OPEN', ownerWorkerId: 'fixture-worker', generation: 1, fencingToken: 1, profileKey: 'fixture-profile', reusePolicy: 'NEW_PAGE', idleTtlSeconds: 300, maxLifetimeSeconds: 3600, expiresAt: new Date(now.getTime() + 3600_000), authControlActorId: admin.id, authControlTokenHash: 'fixture-control-token-hash', authControlExpiresAt: new Date(now.getTime() + 3600_000) })
    const before = await api.getCredential(db, account.id, admin)
    await expect(api.clearCredential(db, account.id, { expectedRevision: before.revision }, admin, true)).rejects.toMatchObject({ code: 'RESOURCE_BUSY' })
    await expect(targets.updateAccount(target.id, account.id, { clearPassword: true, expectedRevision: before.revision }, admin)).rejects.toMatchObject({ code: 'RESOURCE_BUSY' })
    expect((await api.getCredential(db, account.id, admin)).currentVersionId).toBe(before.currentVersionId)
  })
}, 60_000)
