-- Native baseline at logical schema 0015. IDs are generated by the application.

CREATE TABLE `attempts` (
  `id` VARCHAR(36) NOT NULL,
  `step_run_id` VARCHAR(36) NOT NULL,
  `attempt_no` INT NOT NULL,
  `status` VARCHAR(256) NOT NULL,
  `started_at` DATETIME(3) NOT NULL,
  `finished_at` DATETIME(3),
  `output` JSON,
  `error` JSON,
  CONSTRAINT `attempts_no_check` CHECK ((attempt_no >= 1)),
  CONSTRAINT `attempts_pkey` PRIMARY KEY (id),
  CONSTRAINT `attempts_status_check` CHECK ((status IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `browser_sessions` (
  `id` VARCHAR(36) NOT NULL,
  `target_id` VARCHAR(36) NOT NULL,
  `target_account_id` VARCHAR(36) NOT NULL,
  `status` VARCHAR(256) NOT NULL,
  `health` LONGTEXT NOT NULL DEFAULT ('UNKNOWN'),
  `auth_state` LONGTEXT NOT NULL DEFAULT ('UNKNOWN'),
  `owner_worker_id` VARCHAR(256) NOT NULL,
  `generation` INT NOT NULL,
  `fencing_token` INT NOT NULL DEFAULT 0,
  `version` INT NOT NULL DEFAULT 0,
  `profile_key` LONGTEXT NOT NULL,
  `reuse_policy` LONGTEXT NOT NULL,
  `idle_ttl_seconds` INT NOT NULL,
  `max_lifetime_seconds` INT NOT NULL,
  `expires_at` DATETIME(3) NOT NULL,
  `last_used_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `auth_hold_worker_id` LONGTEXT,
  `auth_hold_expires_at` DATETIME(3),
  `close_reason` LONGTEXT,
  `closed_at` DATETIME(3),
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `browser_sessions_auth_hold_check` CHECK (((auth_hold_worker_id IS NULL) = (auth_hold_expires_at IS NULL))),
  CONSTRAINT `browser_sessions_auth_state_check` CHECK ((auth_state IN ('UNKNOWN', 'AUTHENTICATED', 'EXPIRED'))),
  CONSTRAINT `browser_sessions_closed_check` CHECK (((status <> 'CLOSED') OR ((closed_at IS NOT NULL) AND (close_reason IS NOT NULL)))),
  CONSTRAINT `browser_sessions_generation_check` CHECK (((generation >= 1) AND (fencing_token >= 0) AND (version >= 0))),
  CONSTRAINT `browser_sessions_health_check` CHECK ((health IN ('UNKNOWN', 'HEALTHY', 'UNHEALTHY'))),
  CONSTRAINT `browser_sessions_pkey` PRIMARY KEY (id),
  CONSTRAINT `browser_sessions_reuse_policy_check` CHECK ((reuse_policy IN ('REUSE_PAGE', 'NEW_PAGE', 'RECREATE_SESSION'))),
  CONSTRAINT `browser_sessions_status_check` CHECK ((status IN ('CREATING', 'OPEN', 'CLOSING', 'CLOSED', 'LOST'))),
  CONSTRAINT `browser_sessions_ttl_check` CHECK (((idle_ttl_seconds > 0) AND (max_lifetime_seconds > idle_ttl_seconds))),
  live_slot INT GENERATED ALWAYS AS (CASE WHEN status IN ('CREATING','OPEN','CLOSING','LOST') THEN 1 ELSE NULL END) STORED
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `console_account_roles` (
  `console_account_id` VARCHAR(36) NOT NULL,
  `console_role_id` VARCHAR(36) NOT NULL,
  `assigned_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `assigned_by_console_account_id` VARCHAR(36),
  CONSTRAINT `console_account_roles_pkey` PRIMARY KEY (console_account_id, console_role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `console_accounts` (
  `id` VARCHAR(36) NOT NULL,
  `display_name` LONGTEXT NOT NULL,
  `email` VARCHAR(320),
  `status` VARCHAR(256) NOT NULL DEFAULT 'active',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `console_accounts_pkey` PRIMARY KEY (id),
  CONSTRAINT `console_accounts_status_check` CHECK ((status IN ('active', 'disabled'))),
  email_normalized VARCHAR(320) GENERATED ALWAYS AS (LOWER(email)) STORED
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `console_audit_events` (
  `id` VARCHAR(36) NOT NULL,
  `actor_console_account_id` VARCHAR(36),
  `action` LONGTEXT NOT NULL,
  `resource` LONGTEXT NOT NULL,
  `resource_id` VARCHAR(36),
  `summary` LONGTEXT NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `console_audit_events_pkey` PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `console_identities` (
  `id` VARCHAR(36) NOT NULL,
  `console_account_id` VARCHAR(36) NOT NULL,
  `provider` VARCHAR(64) NOT NULL,
  `subject` VARCHAR(512) NOT NULL,
  `secret` LONGTEXT,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `last_used_at` DATETIME(3),
  CONSTRAINT `console_identities_pkey` PRIMARY KEY (id),
  CONSTRAINT `console_identities_secret_check` CHECK ((((provider = 'local') AND (secret IS NOT NULL)) OR ((provider <> 'local') AND (secret IS NULL))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `console_role_permissions` (
  `console_role_id` VARCHAR(36) NOT NULL,
  `permission` VARCHAR(128) NOT NULL,
  CONSTRAINT `console_role_permissions_pkey` PRIMARY KEY (console_role_id, permission)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `console_roles` (
  `id` VARCHAR(36) NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  `name` LONGTEXT NOT NULL,
  `description` LONGTEXT,
  `kind` LONGTEXT NOT NULL DEFAULT ('custom'),
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `console_roles_kind_check` CHECK ((kind IN ('system', 'custom'))),
  CONSTRAINT `console_roles_pkey` PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `evidences` (
  `id` VARCHAR(36) NOT NULL,
  `run_id` VARCHAR(36) NOT NULL,
  `step_run_id` VARCHAR(36),
  `attempt_id` VARCHAR(36),
  `type` LONGTEXT NOT NULL,
  `schema_version` INT NOT NULL DEFAULT 1,
  `payload` JSON,
  `object_key` VARCHAR(512),
  `content_type` LONGTEXT,
  `byte_size` INT,
  `digest` LONGTEXT,
  `missing_reason` LONGTEXT,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `status` VARCHAR(256) NOT NULL DEFAULT 'available',
  `object_id` VARCHAR(36),
  `upload_attempts` INT NOT NULL DEFAULT 0,
  CONSTRAINT `evidences_pkey` PRIMARY KEY (id),
  CONSTRAINT `evidences_status_check` CHECK ((status IN ('pending', 'available', 'missing'))),
  CONSTRAINT `evidences_status_missing_reason_check` CHECK ((((status = 'missing') AND (missing_reason IS NOT NULL)) OR ((status <> 'missing') AND (missing_reason IS NULL)))),
  CONSTRAINT `evidences_type_check` CHECK ((type IN ('input', 'output', 'error', 'screenshot', 'log', 'trace'))),
  CONSTRAINT `evidences_upload_attempts_check` CHECK ((upload_attempts >= 0)),
  incomplete_slot INT GENERATED ALWAYS AS (CASE WHEN type = 'error' AND JSON_UNQUOTE(JSON_EXTRACT(payload, '$.code')) = 'EVIDENCE_INCOMPLETE' THEN 1 ELSE NULL END) STORED
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `recording_drafts` (
  `id` VARCHAR(36) NOT NULL,
  `target_id` VARCHAR(36) NOT NULL,
  `created_by_console_account_id` VARCHAR(36) NOT NULL,
  `recording_id` VARCHAR(36) NOT NULL,
  `source_version` LONGTEXT NOT NULL,
  `idempotency_key` VARCHAR(256) NOT NULL,
  `payload_digest` LONGTEXT NOT NULL,
  `name` LONGTEXT NOT NULL,
  `event_count` INT NOT NULL,
  `item_count` INT NOT NULL,
  `unresolved_count` INT NOT NULL,
  `events` JSON NOT NULL,
  `items` JSON NOT NULL,
  `diagnostics` JSON NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `recording_drafts_diagnostics_array` CHECK ((LOWER(JSON_TYPE(`diagnostics`)) = 'array')),
  CONSTRAINT `recording_drafts_events_array` CHECK ((LOWER(JSON_TYPE(`events`)) = 'array')),
  CONSTRAINT `recording_drafts_items_array` CHECK ((LOWER(JSON_TYPE(`items`)) = 'array')),
  CONSTRAINT `recording_drafts_pkey` PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `run_leases` (
  `id` VARCHAR(36) NOT NULL,
  `run_id` VARCHAR(36) NOT NULL,
  `fencing_token` INT NOT NULL,
  `holder_worker_id` VARCHAR(256) NOT NULL,
  `status` VARCHAR(256) NOT NULL,
  `acquired_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `heartbeat_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at` DATETIME(3) NOT NULL,
  `released_at` DATETIME(3),
  `release_reason` LONGTEXT,
  CONSTRAINT `run_leases_pkey` PRIMARY KEY (id),
  CONSTRAINT `run_leases_released_check` CHECK (((status = 'ACTIVE') = (released_at IS NULL))),
  CONSTRAINT `run_leases_status_check` CHECK ((status IN ('ACTIVE', 'RELEASED', 'EXPIRED', 'REVOKED'))),
  CONSTRAINT `run_leases_token_check` CHECK ((fencing_token >= 1)),
  active_slot INT GENERATED ALWAYS AS (CASE WHEN status = 'ACTIVE' THEN 1 ELSE NULL END) STORED
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `runs` (
  `id` VARCHAR(36) NOT NULL,
  `target_id` VARCHAR(36) NOT NULL,
  `scenario_id` VARCHAR(36) NOT NULL,
  `scenario_version_id` VARCHAR(36) NOT NULL,
  `target_account_id` VARCHAR(36),
  `created_by_console_account_id` VARCHAR(36) NOT NULL,
  `status` VARCHAR(256) NOT NULL,
  `cancel_requested_at` DATETIME(3),
  `started_at` DATETIME(3),
  `finished_at` DATETIME(3),
  `snapshot` JSON NOT NULL,
  `snapshot_digest` LONGTEXT NOT NULL,
  `context` JSON NOT NULL,
  `idempotency_key` VARCHAR(256),
  `idempotency_digest` LONGTEXT,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `evidence_status` LONGTEXT NOT NULL DEFAULT ('PENDING'),
  CONSTRAINT `runs_evidence_status_check` CHECK ((evidence_status IN ('PENDING', 'COMPLETE', 'INCOMPLETE'))),
  CONSTRAINT `runs_idempotency_pair` CHECK (((idempotency_key IS NULL) = (idempotency_digest IS NULL))),
  CONSTRAINT `runs_pkey` PRIMARY KEY (id),
  CONSTRAINT `runs_status_check` CHECK ((status IN ('QUEUED', 'RUNNING', 'RECOVERING', 'WAITING_FOR_AUTH', 'NEEDS_REVIEW', 'SUCCEEDED', 'FAILED', 'CANCELLED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `scenario_drafts` (
  `scenario_id` VARCHAR(36) NOT NULL,
  `revision` INT NOT NULL,
  `document` JSON NOT NULL,
  `updated_by_console_account_id` VARCHAR(36) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `scenario_drafts_document_object` CHECK ((LOWER(JSON_TYPE(`document`)) = 'object')),
  CONSTRAINT `scenario_drafts_pkey` PRIMARY KEY (scenario_id),
  CONSTRAINT `scenario_drafts_revision_check` CHECK ((revision >= 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `scenario_versions` (
  `id` VARCHAR(36) NOT NULL,
  `scenario_id` VARCHAR(36) NOT NULL,
  `version_no` INT,
  `definition` JSON NOT NULL,
  `created_by_console_account_id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `kind` LONGTEXT NOT NULL DEFAULT ('published'),
  `compiler_version` INT NOT NULL DEFAULT 1,
  `source_digest` VARCHAR(64) NOT NULL,
  CONSTRAINT `scenario_versions_definition_object` CHECK ((LOWER(JSON_TYPE(`definition`)) = 'object')),
  CONSTRAINT `scenario_versions_kind_check` CHECK ((kind IN ('published', 'trial'))),
  CONSTRAINT `scenario_versions_no_check` CHECK ((version_no >= 1)),
  CONSTRAINT `scenario_versions_pkey` PRIMARY KEY (id),
  CONSTRAINT `scenario_versions_published_no_check` CHECK ((((kind = 'published') AND (version_no IS NOT NULL)) OR ((kind = 'trial') AND (version_no IS NULL)))),
  trial_slot INT GENERATED ALWAYS AS (CASE WHEN kind = 'trial' THEN 1 ELSE NULL END) STORED
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `scenarios` (
  `id` VARCHAR(36) NOT NULL,
  `target_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `status` VARCHAR(256) NOT NULL DEFAULT 'active',
  `created_by_console_account_id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `scenarios_pkey` PRIMARY KEY (id),
  CONSTRAINT `scenarios_status_check` CHECK ((status IN ('active', 'disabled')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `secrets` (
  `id` VARCHAR(36) NOT NULL,
  `provider` LONGTEXT NOT NULL,
  `ciphertext` LONGBLOB NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `secrets_pkey` PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `session_leases` (
  `id` VARCHAR(36) NOT NULL,
  `session_id` VARCHAR(36) NOT NULL,
  `session_generation` INT NOT NULL,
  `session_fencing_token` INT NOT NULL,
  `run_id` VARCHAR(36) NOT NULL,
  `run_fencing_token` INT,
  `holder_worker_id` VARCHAR(256) NOT NULL,
  `status` VARCHAR(256) NOT NULL,
  `acquired_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `heartbeat_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at` DATETIME(3) NOT NULL,
  `released_at` DATETIME(3),
  `release_reason` LONGTEXT,
  CONSTRAINT `session_leases_fencing_check` CHECK (((session_generation >= 1) AND (session_fencing_token >= 1) AND ((run_fencing_token IS NULL) OR (run_fencing_token >= 1)))),
  CONSTRAINT `session_leases_pkey` PRIMARY KEY (id),
  CONSTRAINT `session_leases_released_check` CHECK (((status = 'ACTIVE') = (released_at IS NULL))),
  CONSTRAINT `session_leases_run_fencing_active_check` CHECK (((status <> 'ACTIVE') OR (run_fencing_token IS NOT NULL))),
  CONSTRAINT `session_leases_status_check` CHECK ((status IN ('ACTIVE', 'RELEASED', 'EXPIRED', 'REVOKED'))),
  active_slot INT GENERATED ALWAYS AS (CASE WHEN status = 'ACTIVE' THEN 1 ELSE NULL END) STORED
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `step_runs` (
  `id` VARCHAR(36) NOT NULL,
  `run_id` VARCHAR(36) NOT NULL,
  `step_id` VARCHAR(36) NOT NULL,
  `ordinal` INT NOT NULL,
  `status` VARCHAR(256) NOT NULL,
  `started_at` DATETIME(3),
  `finished_at` DATETIME(3),
  CONSTRAINT `step_runs_ordinal_check` CHECK ((ordinal >= 0)),
  CONSTRAINT `step_runs_pkey` PRIMARY KEY (id),
  CONSTRAINT `step_runs_status_check` CHECK ((status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', 'CANCELLED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `stored_objects` (
  `id` VARCHAR(36) NOT NULL,
  `object_key` VARCHAR(512) NOT NULL,
  `run_id` VARCHAR(36) NOT NULL,
  `status` VARCHAR(256) NOT NULL,
  `content_type` LONGTEXT,
  `byte_size` INT,
  `digest` LONGTEXT,
  `retain_until` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `available_at` DATETIME(3),
  `purged_at` DATETIME(3),
  `purge_reason` LONGTEXT,
  `purge_attempts` INT NOT NULL DEFAULT 0,
  `last_purge_error_at` DATETIME(3),
  CONSTRAINT `stored_objects_byte_size_check` CHECK (((byte_size IS NULL) OR (byte_size >= 0))),
  CONSTRAINT `stored_objects_pkey` PRIMARY KEY (id),
  CONSTRAINT `stored_objects_purge_reason_check` CHECK (((purge_reason IS NULL) OR (purge_reason IN ('expired', 'upload_incomplete')))),
  CONSTRAINT `stored_objects_status_check` CHECK ((status IN ('pending', 'available', 'purged')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `target_accounts` (
  `id` VARCHAR(36) NOT NULL,
  `target_id` VARCHAR(36) NOT NULL,
  `display_name` LONGTEXT NOT NULL,
  `username` VARCHAR(256) NOT NULL,
  `secret_provider` LONGTEXT,
  `secret_id` VARCHAR(36),
  `status` VARCHAR(256) NOT NULL DEFAULT 'active',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `target_accounts_pkey` PRIMARY KEY (id),
  CONSTRAINT `target_accounts_secret_ref_pair` CHECK ((((secret_id IS NULL) AND (secret_provider IS NULL)) OR ((secret_id IS NOT NULL) AND (secret_provider IS NOT NULL)))),
  CONSTRAINT `target_accounts_status_check` CHECK ((status IN ('active', 'disabled')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `targets` (
  `id` VARCHAR(36) NOT NULL,
  `code` VARCHAR(256) NOT NULL,
  `name` LONGTEXT NOT NULL,
  `entry_url` LONGTEXT NOT NULL,
  `login_url` LONGTEXT,
  `auth_method` LONGTEXT NOT NULL DEFAULT ('password'),
  `captcha_mode` LONGTEXT NOT NULL DEFAULT ('none'),
  `status` VARCHAR(256) NOT NULL DEFAULT 'active',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `login_fields` JSON,
  CONSTRAINT `targets_auth_method_check` CHECK ((auth_method IN ('password', 'manual'))),
  CONSTRAINT `targets_captcha_mode_check` CHECK ((captcha_mode IN ('none', 'image', 'slider', 'sms', 'other'))),
  CONSTRAINT `targets_login_fields_object` CHECK (((login_fields IS NULL) OR (LOWER(JSON_TYPE(`login_fields`)) = 'object'))),
  CONSTRAINT `targets_pkey` PRIMARY KEY (id),
  CONSTRAINT `targets_status_check` CHECK ((status IN ('active', 'disabled')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE `workers` (
  `id` VARCHAR(256) NOT NULL,
  `instance_id` VARCHAR(36) NOT NULL,
  `status` VARCHAR(256) NOT NULL,
  `capacity` INT NOT NULL,
  `heartbeat_at` DATETIME(3) NOT NULL,
  `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `stopped_at` DATETIME(3),
  `max_sessions` INT NOT NULL DEFAULT 2,
  CONSTRAINT `workers_capacity_check` CHECK ((capacity >= 1)),
  CONSTRAINT `workers_max_sessions_check` CHECK ((max_sessions >= 1)),
  CONSTRAINT `workers_pkey` PRIMARY KEY (id),
  CONSTRAINT `workers_status_check` CHECK ((status IN ('READY', 'DRAINING', 'STOPPED', 'LOST')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE UNIQUE INDEX attempts_step_no_idx ON attempts (step_run_id, attempt_no);

CREATE UNIQUE INDEX browser_sessions_key_live_idx ON browser_sessions (target_id, target_account_id, live_slot);

CREATE INDEX browser_sessions_owner_idx ON browser_sessions (owner_worker_id, status);

CREATE INDEX browser_sessions_reap_idx ON browser_sessions (status, last_used_at);

CREATE INDEX console_account_roles_role_idx ON console_account_roles (console_role_id);

CREATE UNIQUE INDEX console_accounts_email_idx ON console_accounts (email_normalized);

CREATE INDEX console_audit_events_actor_idx ON console_audit_events (actor_console_account_id);

CREATE INDEX console_audit_events_created_idx ON console_audit_events (created_at DESC);

CREATE INDEX console_identities_account_idx ON console_identities (console_account_id);

CREATE UNIQUE INDEX console_identities_provider_subject_idx ON console_identities (provider, subject);

CREATE INDEX console_role_permissions_perm_idx ON console_role_permissions (permission);

CREATE UNIQUE INDEX console_roles_key_idx ON console_roles (`key`);

CREATE INDEX evidences_attempt_id_idx ON evidences (attempt_id);

CREATE INDEX evidences_run_created_idx ON evidences (run_id, created_at);

CREATE UNIQUE INDEX evidences_run_incomplete_idx ON evidences (run_id, incomplete_slot);

CREATE INDEX evidences_status_idx ON evidences (status, created_at);

CREATE UNIQUE INDEX recording_drafts_actor_idempotency_idx ON recording_drafts (created_by_console_account_id, idempotency_key);

CREATE INDEX recording_drafts_created_at_idx ON recording_drafts (created_at);

CREATE INDEX recording_drafts_target_id_idx ON recording_drafts (target_id);

CREATE UNIQUE INDEX run_leases_active_idx ON run_leases (run_id, active_slot);

CREATE INDEX run_leases_holder_idx ON run_leases (holder_worker_id, status);

CREATE INDEX run_leases_reap_idx ON run_leases (status, expires_at);

CREATE UNIQUE INDEX run_leases_token_idx ON run_leases (run_id, fencing_token);

CREATE INDEX runs_claim_idx ON runs (status, created_at, id);

CREATE UNIQUE INDEX runs_idempotency_idx ON runs (created_by_console_account_id, idempotency_key);

CREATE INDEX scenario_drafts_updated_at_idx ON scenario_drafts (updated_at);

CREATE UNIQUE INDEX scenario_versions_scenario_no_idx ON scenario_versions (scenario_id, version_no);

CREATE UNIQUE INDEX scenario_versions_trial_digest_idx ON scenario_versions (scenario_id, source_digest, trial_slot);

CREATE INDEX scenarios_target_id_idx ON scenarios (target_id);

CREATE UNIQUE INDEX scenarios_target_name_idx ON scenarios (target_id, name);

CREATE UNIQUE INDEX session_leases_active_idx ON session_leases (session_id, active_slot);

CREATE INDEX session_leases_holder_idx ON session_leases (holder_worker_id, status);

CREATE INDEX session_leases_reap_idx ON session_leases (status, expires_at);

CREATE INDEX session_leases_run_id_idx ON session_leases (run_id);

CREATE UNIQUE INDEX step_runs_run_ordinal_idx ON step_runs (run_id, ordinal);

CREATE UNIQUE INDEX step_runs_run_step_idx ON step_runs (run_id, step_id);

CREATE UNIQUE INDEX stored_objects_object_key_idx ON stored_objects (object_key);

CREATE INDEX stored_objects_pending_idx ON stored_objects (status, created_at);

CREATE INDEX stored_objects_purge_idx ON stored_objects (status, purge_attempts, retain_until);

CREATE INDEX stored_objects_run_id_idx ON stored_objects (run_id);

CREATE UNIQUE INDEX target_accounts_id_target_id_idx ON target_accounts (id, target_id);

CREATE INDEX target_accounts_target_id_idx ON target_accounts (target_id);

CREATE UNIQUE INDEX target_accounts_target_username_idx ON target_accounts (target_id, username);

CREATE UNIQUE INDEX targets_code_idx ON targets (code);

ALTER TABLE `attempts` ADD CONSTRAINT `attempts_step_run_id_fkey` FOREIGN KEY (step_run_id) REFERENCES step_runs(id) ON DELETE RESTRICT;

ALTER TABLE `browser_sessions` ADD CONSTRAINT `browser_sessions_target_account_fkey` FOREIGN KEY (target_account_id, target_id) REFERENCES target_accounts(id, target_id) ON DELETE RESTRICT;

ALTER TABLE `console_account_roles` ADD CONSTRAINT `console_account_roles_assigned_by_console_account_id_fkey` FOREIGN KEY (assigned_by_console_account_id) REFERENCES console_accounts(id) ON DELETE SET NULL;

ALTER TABLE `console_account_roles` ADD CONSTRAINT `console_account_roles_console_account_id_fkey` FOREIGN KEY (console_account_id) REFERENCES console_accounts(id) ON DELETE CASCADE;

ALTER TABLE `console_account_roles` ADD CONSTRAINT `console_account_roles_console_role_id_fkey` FOREIGN KEY (console_role_id) REFERENCES console_roles(id) ON DELETE RESTRICT;

ALTER TABLE `console_audit_events` ADD CONSTRAINT `console_audit_events_actor_console_account_id_fkey` FOREIGN KEY (actor_console_account_id) REFERENCES console_accounts(id) ON DELETE SET NULL;

ALTER TABLE `console_identities` ADD CONSTRAINT `console_identities_console_account_id_fkey` FOREIGN KEY (console_account_id) REFERENCES console_accounts(id) ON DELETE CASCADE;

ALTER TABLE `console_role_permissions` ADD CONSTRAINT `console_role_permissions_console_role_id_fkey` FOREIGN KEY (console_role_id) REFERENCES console_roles(id) ON DELETE CASCADE;

ALTER TABLE `evidences` ADD CONSTRAINT `evidences_attempt_id_fkey` FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE RESTRICT;

ALTER TABLE `evidences` ADD CONSTRAINT `evidences_object_id_stored_objects_fkey` FOREIGN KEY (object_id) REFERENCES stored_objects(id) ON DELETE RESTRICT;

ALTER TABLE `evidences` ADD CONSTRAINT `evidences_object_key_stored_objects_fkey` FOREIGN KEY (object_key) REFERENCES stored_objects(object_key) ON DELETE RESTRICT;

ALTER TABLE `evidences` ADD CONSTRAINT `evidences_run_id_fkey` FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE RESTRICT;

ALTER TABLE `evidences` ADD CONSTRAINT `evidences_step_run_id_fkey` FOREIGN KEY (step_run_id) REFERENCES step_runs(id) ON DELETE RESTRICT;

ALTER TABLE `recording_drafts` ADD CONSTRAINT `recording_drafts_created_by_console_account_id_fkey` FOREIGN KEY (created_by_console_account_id) REFERENCES console_accounts(id) ON DELETE RESTRICT;

ALTER TABLE `recording_drafts` ADD CONSTRAINT `recording_drafts_target_id_fkey` FOREIGN KEY (target_id) REFERENCES targets(id) ON DELETE RESTRICT;

ALTER TABLE `run_leases` ADD CONSTRAINT `run_leases_run_id_fkey` FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE RESTRICT;

ALTER TABLE `runs` ADD CONSTRAINT `runs_created_by_console_account_id_fkey` FOREIGN KEY (created_by_console_account_id) REFERENCES console_accounts(id) ON DELETE RESTRICT;

ALTER TABLE `runs` ADD CONSTRAINT `runs_scenario_id_fkey` FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE RESTRICT;

ALTER TABLE `runs` ADD CONSTRAINT `runs_scenario_version_id_fkey` FOREIGN KEY (scenario_version_id) REFERENCES scenario_versions(id) ON DELETE RESTRICT;

ALTER TABLE `runs` ADD CONSTRAINT `runs_target_account_id_fkey` FOREIGN KEY (target_account_id) REFERENCES target_accounts(id) ON DELETE RESTRICT;

ALTER TABLE `runs` ADD CONSTRAINT `runs_target_id_fkey` FOREIGN KEY (target_id) REFERENCES targets(id) ON DELETE RESTRICT;

ALTER TABLE `scenario_drafts` ADD CONSTRAINT `scenario_drafts_scenario_id_fkey` FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE RESTRICT;

ALTER TABLE `scenario_drafts` ADD CONSTRAINT `scenario_drafts_updated_by_console_account_id_fkey` FOREIGN KEY (updated_by_console_account_id) REFERENCES console_accounts(id) ON DELETE RESTRICT;

ALTER TABLE `scenario_versions` ADD CONSTRAINT `scenario_versions_created_by_console_account_id_fkey` FOREIGN KEY (created_by_console_account_id) REFERENCES console_accounts(id) ON DELETE RESTRICT;

ALTER TABLE `scenario_versions` ADD CONSTRAINT `scenario_versions_scenario_id_fkey` FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE RESTRICT;

ALTER TABLE `scenarios` ADD CONSTRAINT `scenarios_created_by_console_account_id_fkey` FOREIGN KEY (created_by_console_account_id) REFERENCES console_accounts(id) ON DELETE RESTRICT;

ALTER TABLE `scenarios` ADD CONSTRAINT `scenarios_target_id_fkey` FOREIGN KEY (target_id) REFERENCES targets(id) ON DELETE RESTRICT;

ALTER TABLE `session_leases` ADD CONSTRAINT `session_leases_run_id_fkey` FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE RESTRICT;

ALTER TABLE `session_leases` ADD CONSTRAINT `session_leases_session_id_fkey` FOREIGN KEY (session_id) REFERENCES browser_sessions(id) ON DELETE RESTRICT;

ALTER TABLE `step_runs` ADD CONSTRAINT `step_runs_run_id_fkey` FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE RESTRICT;

ALTER TABLE `stored_objects` ADD CONSTRAINT `stored_objects_run_id_fkey` FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE RESTRICT;

ALTER TABLE `target_accounts` ADD CONSTRAINT `target_accounts_secret_id_fkey` FOREIGN KEY (secret_id) REFERENCES secrets(id) ON DELETE RESTRICT;

ALTER TABLE `target_accounts` ADD CONSTRAINT `target_accounts_target_id_fkey` FOREIGN KEY (target_id) REFERENCES targets(id) ON DELETE RESTRICT;

INSERT INTO `console_roles` (`id`, `key`, `name`, `description`, `kind`, `created_at`, `updated_at`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'admin', 'Administrator', 'Full access, including identity and permission management.', 'system', '2026-09-13 09:47:09.309', '2026-09-13 09:47:09.309');

INSERT INTO `console_roles` (`id`, `key`, `name`, `description`, `kind`, `created_at`, `updated_at`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'operator', 'Operator', 'Run and edit workflows. Cannot manage accounts or roles.', 'system', '2026-09-13 09:47:09.309', '2026-09-13 09:47:09.309');

INSERT INTO `console_roles` (`id`, `key`, `name`, `description`, `kind`, `created_at`, `updated_at`) VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'viewer', 'Viewer', 'Read-only access to the console.', 'system', '2026-09-13 09:47:09.309', '2026-09-13 09:47:09.309');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'audit:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'settings:write');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'settings:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'target:delete');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'target:write');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'target:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'run:cancel');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'run:execute');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'run:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'workflow:delete');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'workflow:write');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'workflow:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'role:delete');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'role:write');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'role:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'account:delete');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'account:write');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'account:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'audit:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'settings:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'target:delete');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'target:write');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'target:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'run:cancel');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'run:execute');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'run:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'workflow:delete');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'workflow:write');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'workflow:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'role:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'account:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'audit:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'settings:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'target:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'run:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'workflow:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'role:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'account:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'session:dispose');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'session:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'session:dispose');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'session:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('9342715d-ea0d-4f89-9b7d-cff4903eeb1a', 'session:read');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('11280570-f874-4939-831c-fc7db1f0d8e0', 'run:review');

INSERT INTO `console_role_permissions` (`console_role_id`, `permission`) VALUES ('a580f5e8-a53e-4b25-b3fa-22ef9e0647e0', 'run:review');

CREATE TRIGGER scenario_versions_immutable BEFORE UPDATE ON scenario_versions FOR EACH ROW BEGIN IF NOT (OLD.definition <=> NEW.definition) OR NOT (OLD.version_no <=> NEW.version_no) OR NOT (OLD.scenario_id <=> NEW.scenario_id) OR NOT (OLD.kind <=> NEW.kind) OR NOT (OLD.compiler_version <=> NEW.compiler_version) OR NOT (OLD.source_digest <=> NEW.source_digest) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'scenario_versions immutable'; END IF; END;

CREATE TRIGGER runs_snapshot_immutable BEFORE UPDATE ON runs FOR EACH ROW BEGIN IF NOT (OLD.snapshot <=> NEW.snapshot) OR NOT (OLD.snapshot_digest <=> NEW.snapshot_digest) OR NOT (OLD.target_id <=> NEW.target_id) OR NOT (OLD.scenario_id <=> NEW.scenario_id) OR NOT (OLD.scenario_version_id <=> NEW.scenario_version_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'runs immutable'; END IF; END;

CREATE TRIGGER attempts_closed_immutable BEFORE UPDATE ON attempts FOR EACH ROW BEGIN IF OLD.status IN ('SUCCEEDED', 'FAILED', 'CANCELLED') AND (NOT (OLD.status <=> NEW.status) OR NOT (OLD.output <=> NEW.output) OR NOT (OLD.error <=> NEW.error) OR NOT (OLD.finished_at <=> NEW.finished_at)) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'attempts immutable'; END IF; END;
